#!/usr/bin/env bash
# scripts/pr-body.sh: every PR body lives in one directory, names cannot escape it,
# and create/update hand gh a --body-file inside it.

set -eu

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
PRB="$ROOT/scripts/pr-body.sh"

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT
export PR_BODY_DIR="$tmpdir/pr-bodies"

fail() { echo "FAIL: $*" >&2; exit 1; }

# A fake `gh` that records its argv and the body file's content at call time.
mkdir -p "$tmpdir/bin"
cat > "$tmpdir/bin/gh" <<'FAKE'
#!/bin/sh
printf '%s\n' "$*" > "$FAKE_GH_ARGS"
prev=''
for a in "$@"; do
  if [ "$prev" = --body-file ]; then cat "$a" > "$FAKE_GH_BODY"; fi
  prev="$a"
done
FAKE
chmod +x "$tmpdir/bin/gh"
export PATH="$tmpdir/bin:$PATH"
export FAKE_GH_ARGS="$tmpdir/gh-args" FAKE_GH_BODY="$tmpdir/gh-body"

# --- 1. path creates the directory and returns a path inside it --------------
p="$(bash "$PRB" path issue-871)"
[ "$p" = "$PR_BODY_DIR/issue-871.md" ] || fail "1: unexpected path $p"
[ -d "$PR_BODY_DIR" ] || fail "1: directory not created"
echo "ok 1: path is inside the body directory"

# --- 2. names cannot escape the directory or hide -----------------------------
for bad in '../evil' 'a/b' '.hidden' '' 'x..y' '/etc/passwd' 'name with space'; do
  if bash "$PRB" path "$bad" >/dev/null 2>&1; then fail "2: accepted bad name '$bad'"; fi
done
[ ! -e "$tmpdir/evil.md" ] || fail "2: wrote outside the directory"
echo "ok 2: traversal, separators, dotfiles and empty names are rejected"

# --- 3. new seeds a template, never overwrites, --issue adds Closes ----------
bash "$PRB" new seeded --issue 12 >/dev/null
grep -q 'TODO(pr-body)' "$PR_BODY_DIR/seeded.md" || fail "3: template has no placeholders"
grep -q '^Closes #12$' "$PR_BODY_DIR/seeded.md" || fail "3: --issue did not add Closes"
echo custom > "$PR_BODY_DIR/seeded.md"
bash "$PRB" new seeded >/dev/null 2>&1
[ "$(cat "$PR_BODY_DIR/seeded.md")" = custom ] || fail "3: new overwrote an existing body"
echo "ok 3: template seeded, existing body kept"

# --- 4. write is atomic from stdin and refuses empty --------------------------
printf '## Summary\n\nhello\n' | bash "$PRB" write w1 >/dev/null
grep -q hello "$PR_BODY_DIR/w1.md" || fail "4: write did not store stdin"
if bash "$PRB" write w2 </dev/null >/dev/null 2>&1; then fail "4: wrote an empty body"; fi
[ ! -e "$PR_BODY_DIR/w2.md" ] || fail "4: empty write left a file behind"
ls "$PR_BODY_DIR" | grep -q '\.tmp\.' && fail "4: temp file leaked"
echo "ok 4: write is atomic and refuses empty input"

# --- 5. check rejects placeholders / missing Summary; flags closing keywords ---
if bash "$PRB" check seeded >/dev/null 2>&1; then fail "5: check passed an unfilled body"; fi
printf 'no headings here\n' | bash "$PRB" write nosummary >/dev/null
if bash "$PRB" check nosummary >/dev/null 2>&1; then fail "5: check passed a body with no Summary"; fi
printf '## Summary\n\nFixes #99 later\n' | bash "$PRB" write closing >/dev/null
bash "$PRB" check closing >"$tmpdir/out5" 2>&1 || fail "5: closing-keyword body should still pass"
grep -q 'will CLOSE' "$tmpdir/out5" || fail "5: closing keyword not surfaced"
echo "ok 5: placeholders and missing Summary fail; closing keywords are surfaced"

# --- 6. create hands gh --body-file inside the directory, with passthrough flags -
printf '## Summary\n\nbody text\n' | bash "$PRB" write good >/dev/null
bash "$PRB" create good --title 'My title' --base main >/dev/null
grep -q -- "pr create --title My title --body-file $PR_BODY_DIR/good.md --base main" "$FAKE_GH_ARGS" \
  || fail "6: unexpected gh args: $(cat "$FAKE_GH_ARGS")"
grep -q 'body text' "$FAKE_GH_BODY" || fail "6: gh did not receive the body"
if bash "$PRB" create good >/dev/null 2>&1; then fail "6: create without --title succeeded"; fi
if bash "$PRB" create seeded --title T >/dev/null 2>&1; then fail "6: create used an unfilled body"; fi
echo "ok 6: create passes --body-file from the directory and checks first"

# --- 7. footer appended to a copy, original untouched, no duplicate ------------
PR_BODY_FOOTER='Generated by test' bash "$PRB" create good --title T >/dev/null
grep -q 'Generated by test' "$FAKE_GH_BODY" || fail "7: footer not added"
grep -q 'Generated by test' "$PR_BODY_DIR/good.md" && fail "7: footer written into the original"
printf '## Summary\n\nx\n\nGenerated by test\n' | bash "$PRB" write hasfooter >/dev/null
PR_BODY_FOOTER='Generated by test' bash "$PRB" create hasfooter --title T >/dev/null
[ "$(grep -c 'Generated by test' "$FAKE_GH_BODY")" -eq 1 ] || fail "7: footer duplicated"
ls "$PR_BODY_DIR" | grep -q '\.footer\.' && fail "7: footer temp copy leaked"
echo "ok 7: footer appended once, to a temporary copy"

# --- 8. update -----------------------------------------------------------------
bash "$PRB" update 42 good >/dev/null
grep -q -- "pr edit 42 --body-file $PR_BODY_DIR/good.md" "$FAKE_GH_ARGS" || fail "8: unexpected gh args: $(cat "$FAKE_GH_ARGS")"
if bash "$PRB" update notanumber good >/dev/null 2>&1; then fail "8: non-numeric PR accepted"; fi
echo "ok 8: update edits by number"

# --- 9. symlinks are refused (a symlink could point anywhere) -------------------
echo secret > "$tmpdir/outside.txt"
ln -s "$tmpdir/outside.txt" "$PR_BODY_DIR/linked.md"
if bash "$PRB" check linked >/dev/null 2>&1; then fail "9: followed a symlinked body"; fi
rm -rf "$tmpdir/linkroot"; ln -s "$PR_BODY_DIR" "$tmpdir/linkroot"
if PR_BODY_DIR="$tmpdir/linkroot" bash "$PRB" path x >/dev/null 2>&1; then fail "9: accepted a symlinked directory"; fi
echo "ok 9: symlinked bodies and directories are refused"

# --- 10. clean removes only old .md files in the directory -----------------------
touch -t 200001010000 "$PR_BODY_DIR/old.md"
touch -t 200001010000 "$tmpdir/unrelated-old.md"
bash "$PRB" clean --days 1 >/dev/null
[ ! -e "$PR_BODY_DIR/old.md" ] || fail "10: old body not cleaned"
[ -e "$PR_BODY_DIR/good.md" ] || fail "10: fresh body removed"
[ -e "$tmpdir/unrelated-old.md" ] || fail "10: clean touched a file outside the directory"
echo "ok 10: clean is confined to the body directory"

echo "all pr-body scenarios passed"
