import type { CivDefinition } from '@/core/types';

export const CIV_DEFINITIONS: CivDefinition[] = [
  {
    id: 'egypt',
    name: 'Egypt',
    color: '#c4a94d',
    bonusName: 'Master Builders',
    bonusDescription: 'Wonders (Monument, Amphitheater) build 30% faster',
    bonusEffect: { type: 'faster_wonders', speedMultiplier: 0.7 },
    personality: {
      traits: ['diplomatic', 'expansionist'],
      warLikelihood: 0.2,
      diplomacyFocus: 0.7,
      expansionDrive: 0.8,
    },
  },
  {
    id: 'rome',
    name: 'Rome',
    color: '#d94a4a',
    bonusName: 'Roman Roads',
    bonusDescription: 'Roads auto-built between cities (free movement bonus)',
    bonusEffect: { type: 'auto_roads' },
    personality: {
      traits: ['aggressive', 'expansionist'],
      warLikelihood: 0.7,
      diplomacyFocus: 0.3,
      expansionDrive: 0.9,
    },
  },
  {
    id: 'greece',
    name: 'Greece',
    color: '#4a90d9',
    bonusName: 'Diplomatic Influence',
    bonusDescription: 'Relationship scores with AI start at +20',
    bonusEffect: { type: 'diplomacy_start_bonus', bonus: 20 },
    personality: {
      traits: ['diplomatic', 'trader'],
      warLikelihood: 0.15,
      diplomacyFocus: 0.9,
      expansionDrive: 0.4,
    },
  },
  {
    id: 'mongolia',
    name: 'Mongolia',
    color: '#4a9b4a',
    bonusName: 'Horse Lords',
    bonusDescription: 'Mounted units get +1 movement point',
    bonusEffect: { type: 'mounted_movement', bonus: 1 },
    personality: {
      traits: ['aggressive'],
      warLikelihood: 0.8,
      diplomacyFocus: 0.2,
      expansionDrive: 0.6,
    },
  },
  {
    id: 'babylon',
    name: 'Babylon',
    color: '#9b4ad9',
    bonusName: 'Cradle of Knowledge',
    bonusDescription: 'Free tech when entering a new era',
    bonusEffect: { type: 'free_tech_on_era' },
    personality: {
      traits: ['diplomatic'],
      warLikelihood: 0.2,
      diplomacyFocus: 0.6,
      expansionDrive: 0.5,
    },
  },
  {
    id: 'zulu',
    name: 'Zulu',
    color: '#d9944a',
    bonusName: 'Rapid Mobilization',
    bonusDescription: 'Military units train 25% faster',
    bonusEffect: { type: 'faster_military', speedMultiplier: 0.75 },
    personality: {
      traits: ['aggressive'],
      warLikelihood: 0.85,
      diplomacyFocus: 0.1,
      expansionDrive: 0.7,
    },
  },
  {
    id: 'china',
    name: 'China',
    color: '#d94a7b',
    bonusName: 'Mandate of Heaven',
    bonusDescription: 'Research speed increased by 20%',
    bonusEffect: { type: 'extra_tech_speed', speedMultiplier: 1.2 },
    personality: {
      traits: ['diplomatic', 'trader'],
      warLikelihood: 0.25,
      diplomacyFocus: 0.7,
      expansionDrive: 0.6,
    },
  },
  {
    id: 'persia',
    name: 'Persia',
    color: '#d9c44a',
    bonusName: 'Silk Road',
    bonusDescription: '+3 gold per trade route',
    bonusEffect: { type: 'trade_route_bonus', bonusGold: 3 },
    personality: {
      traits: ['trader', 'expansionist'],
      warLikelihood: 0.3,
      diplomacyFocus: 0.5,
      expansionDrive: 0.8,
    },
  },
  {
    id: 'england',
    name: 'England',
    color: '#4a6ad9',
    bonusName: 'Rule Britannia',
    bonusDescription: '+1 vision for coastal cities, stronger naval units',
    bonusEffect: { type: 'naval_bonus', visionBonus: 1 },
    personality: {
      traits: ['expansionist', 'aggressive'],
      warLikelihood: 0.5,
      diplomacyFocus: 0.4,
      expansionDrive: 0.85,
    },
  },
  {
    id: 'aztec',
    name: 'Aztec',
    color: '#4ad9a0',
    bonusName: 'Flower Wars',
    bonusDescription: 'Combat victories yield +5 production in nearest city',
    bonusEffect: { type: 'combat_production', productionBonus: 5 },
    personality: {
      traits: ['aggressive'],
      warLikelihood: 0.75,
      diplomacyFocus: 0.15,
      expansionDrive: 0.65,
    },
  },
  {
    id: 'japan',
    name: 'Japan',
    color: '#f0f0f0',
    bonusName: 'Bushido',
    bonusDescription: 'Units fight at full strength when below 50% health',
    bonusEffect: { type: 'bushido' },
    personality: {
      traits: ['aggressive', 'diplomatic'],
      warLikelihood: 0.6,
      diplomacyFocus: 0.5,
      expansionDrive: 0.5,
    },
  },
  {
    id: 'india',
    name: 'India',
    color: '#d97a4a',
    bonusName: 'Subcontinent',
    bonusDescription: 'Cities need 15% less food to grow',
    bonusEffect: { type: 'faster_growth', foodReduction: 0.85 },
    personality: {
      traits: ['diplomatic', 'trader'],
      warLikelihood: 0.15,
      diplomacyFocus: 0.8,
      expansionDrive: 0.6,
    },
  },
  // === M4a New Civilizations ===
  {
    id: 'france',
    name: 'France',
    color: '#1e3a8a',
    bonusName: 'City of Light',
    bonusDescription: 'Cities exert cultural pressure on neighboring tiles, expanding borders faster',
    bonusEffect: { type: 'culture_pressure', radiusBonus: 1 },
    personality: {
      traits: ['diplomatic', 'trader'],
      warLikelihood: 0.3,
      diplomacyFocus: 0.8,
      expansionDrive: 0.6,
    },
  },
  {
    id: 'germany',
    name: 'Germany',
    color: '#78716c',
    bonusName: 'Industrial Powerhouse',
    bonusDescription: '+15% production in all cities',
    bonusEffect: { type: 'industrial_efficiency', productionBonus: 0.15 },
    personality: {
      traits: ['expansionist', 'aggressive'],
      warLikelihood: 0.5,
      diplomacyFocus: 0.4,
      expansionDrive: 0.8,
    },
  },
  {
    id: 'gondor',
    name: 'Gondor',
    color: '#f5f5f4',
    bonusName: 'White City',
    bonusDescription: 'Fortified cities are 25% harder to capture',
    bonusEffect: { type: 'fortified_defense', defenseBonus: 0.25 },
    personality: {
      traits: ['diplomatic', 'aggressive'],
      warLikelihood: 0.4,
      diplomacyFocus: 0.7,
      expansionDrive: 0.5,
    },
  },
  {
    id: 'rohan',
    name: 'Rohan',
    color: '#65a30d',
    bonusName: 'Riders of the Mark',
    bonusDescription: 'Cavalry units heal 10 HP per turn on grassland tiles',
    bonusEffect: { type: 'grassland_cavalry_heal', healPerTurn: 10 },
    personality: {
      traits: ['aggressive', 'expansionist'],
      warLikelihood: 0.6,
      diplomacyFocus: 0.4,
      expansionDrive: 0.7,
    },
  },
  // === M4b1 New Civilizations ===
  {
    id: 'russia',
    name: 'Russia',
    color: '#1e3a5f',
    bonusName: 'Tundra Settlers',
    bonusDescription: 'Expansion & endurance — bonus yields from tundra and snow tiles',
    bonusEffect: { type: 'tundra_bonus', foodBonus: 1, productionBonus: 1 },
    personality: {
      traits: ['expansionist', 'aggressive'],
      warLikelihood: 0.6,
      diplomacyFocus: 0.3,
      expansionDrive: 0.8,
    },
  },
  {
    id: 'ottoman',
    name: 'Ottoman Empire',
    color: '#b91c1c',
    bonusName: 'Great Bombard',
    bonusDescription: 'Siege warfare — bonus damage against fortified cities',
    bonusEffect: { type: 'siege_bonus', damageMultiplier: 1.5 },
    personality: {
      traits: ['aggressive', 'expansionist'],
      warLikelihood: 0.7,
      diplomacyFocus: 0.3,
      expansionDrive: 0.7,
    },
  },
  {
    id: 'shire',
    name: 'The Shire',
    color: '#86efac',
    bonusName: 'Simple Folk',
    bonusDescription: 'Peaceful prosperity — bonus food but weaker military production',
    bonusEffect: { type: 'peaceful_growth', foodBonus: 2, militaryPenalty: 0.25 },
    personality: {
      traits: ['diplomatic', 'trader'],
      warLikelihood: 0.1,
      diplomacyFocus: 0.9,
      expansionDrive: 0.3,
    },
  },
  {
    id: 'isengard',
    name: 'Isengard',
    color: '#374151',
    bonusName: 'Industry of War',
    bonusDescription: 'Industry & war — raze forests for burst production',
    bonusEffect: { type: 'forest_industry', productionBurst: 30 },
    personality: {
      traits: ['aggressive', 'expansionist'],
      warLikelihood: 0.8,
      diplomacyFocus: 0.2,
      expansionDrive: 0.7,
    },
  },
  // === M4c New Civilizations ===
  {
    id: 'spain',
    name: 'Spain',
    color: '#c2410c',
    bonusName: 'Golden Crossroads',
    bonusDescription: 'Bonus rewards from natural wonders and tribal discoveries',
    bonusEffect: { type: 'wonder_rewards', rewardMultiplier: 1.25 },
    personality: {
      traits: ['trader', 'expansionist'],
      warLikelihood: 0.35,
      diplomacyFocus: 0.5,
      expansionDrive: 0.8,
    },
  },
  {
    id: 'viking',
    name: 'Viking',
    color: '#0f766e',
    bonusName: 'Sea Wolves',
    bonusDescription: 'Raiding fleets move faster and see farther along coasts',
    bonusEffect: { type: 'naval_raiding', movementBonus: 1, coastalVisionBonus: 1 },
    personality: {
      traits: ['aggressive', 'expansionist'],
      warLikelihood: 0.75,
      diplomacyFocus: 0.2,
      expansionDrive: 0.75,
    },
  },
  {
    id: 'prydain',
    name: 'Prydain',
    color: '#7c3aed',
    bonusName: 'Stand of the Free',
    bonusDescription: 'Units defending home territory fight with added resolve',
    bonusEffect: { type: 'homeland_defense', defenseBonus: 0.2 },
    personality: {
      traits: ['diplomatic', 'aggressive'],
      warLikelihood: 0.45,
      diplomacyFocus: 0.7,
      expansionDrive: 0.45,
    },
  },
  {
    id: 'annuvin',
    name: 'Annuvin',
    color: '#111827',
    bonusName: 'Court of Shadows',
    bonusDescription: 'Spy networks mature faster and agents gain experience more quickly',
    bonusEffect: { type: 'espionage_growth', experienceBonus: 0.2 },
    personality: {
      traits: ['aggressive', 'trader'],
      warLikelihood: 0.6,
      diplomacyFocus: 0.3,
      expansionDrive: 0.55,
    },
  },
  {
    id: 'wakanda',
    name: 'Wakanda',
    color: '#6b3fa0',
    leaderName: 'TChalla',
    cityNames: ['Birnin Zana', 'Birnin Bashenga', 'Birnin Djata', 'Birnin Kashin', 'Birnin Tchamba', 'Birnin Salan', 'Alkama Fields', 'Jabari Lands'],
    bonusName: 'Shadow Ministries',
    bonusDescription: 'Spies gain experience faster',
    bonusEffect: { type: 'espionage_growth', experienceBonus: 1 },
    personality: {
      traits: ['diplomatic', 'trader'],
      warLikelihood: 0.25,
      diplomacyFocus: 0.8,
      expansionDrive: 0.3,
    },
  },
  {
    id: 'avalon',
    name: 'Avalon',
    color: '#4a8fd9',
    leaderName: 'Arthur',
    cityNames: ['Camelot', 'Tintagel', 'Glastonbury', 'Avalon Isle', 'Caerleon', 'Lyonesse', 'Corbenic', 'Sarras'],
    bonusName: 'Monuments of Glory',
    bonusDescription: 'Legendary wonder rewards are 25% stronger',
    bonusEffect: { type: 'wonder_rewards', rewardMultiplier: 1.25 },
    personality: {
      traits: ['diplomatic', 'expansionist'],
      warLikelihood: 0.35,
      diplomacyFocus: 0.7,
      expansionDrive: 0.6,
    },
  },
  // === M4d New Civilizations ===
  {
    id: 'lothlorien',
    name: 'Lothlorien',
    color: '#4d7c0f',
    bonusName: 'Forest Guardians',
    bonusDescription: 'Forest cities and units are harder to pin down, with stronger forests and hidden movement through woods',
    bonusEffect: { type: 'forest_guardians', defenseBonus: 0.2, visionBonus: 1, concealmentInForest: true, forestYieldBonus: 1 },
    personality: {
      traits: ['diplomatic', 'expansionist'],
      warLikelihood: 0.25,
      diplomacyFocus: 0.7,
      expansionDrive: 0.4,
    },
  },
  {
    id: 'narnia',
    name: 'Narnia',
    color: '#60a5fa',
    bonusName: 'Allied Kingdoms',
    bonusDescription: 'Treaties build stronger relationships and alliances improve empire yields',
    bonusEffect: { type: 'allied_kingdoms', treatyRelationshipBonus: 10, allianceYieldBonus: 2 },
    personality: {
      traits: ['diplomatic', 'aggressive'],
      warLikelihood: 0.35,
      diplomacyFocus: 0.8,
      expansionDrive: 0.5,
    },
  },
  {
    id: 'atlantis',
    name: 'Atlantis',
    color: '#0b7285',
    bonusName: 'Tidebound Knowledge',
    bonusDescription: 'Coastal cities gain extra science and naval forces are built and fight more effectively',
    bonusEffect: { type: 'coastal_science', coastalScienceBonus: 1, navalProductionBonus: 0.15, navalCombatBonus: 0.15 },
    personality: {
      traits: ['trader', 'expansionist'],
      warLikelihood: 0.3,
      diplomacyFocus: 0.6,
      expansionDrive: 0.7,
    },
  },
];

export function getCivDefinition(id: string): CivDefinition | undefined {
  return CIV_DEFINITIONS.find(c => c.id === id);
}
