// AUTO-GENERATED by scripts/generate-earth-maps.ts — do not edit manually.
// Run `yarn generate-maps` to regenerate.
import type { GeoTile } from './geo-map-loader';
import type { HexCoord } from '@/core/types';

type RiverSegment = { from: HexCoord; to: HexCoord };

export const EARTH_TILES: Record<'small' | 'medium' | 'large', GeoTile[]> = {
  small: [],
  medium: [],
  large: [],
};

export const EARTH_START_POSITIONS: Record<'small' | 'medium' | 'large', Record<string, HexCoord>> = {
  small: {},
  medium: {},
  large: {},
};

export const EARTH_RIVERS: Record<'small' | 'medium' | 'large', RiverSegment[]> = {
  small: [],
  medium: [],
  large: [],
};
