import type { BuildingCategory, ImprovementType, ResourceYield, TerrainType, UnitType } from '@/core/types';

export type YieldKind =
  | { kind: 'cityFlat'; yields: Partial<ResourceYield> }
  | {
      kind: 'cityFlatConditional';
      yields: Partial<ResourceYield>;
      requiresAnyBuilding?: string[];
      requiresAllBuildings?: string[];
      requiresBuildingCategory?: BuildingCategory;
      requiresRiver?: boolean;
      requiresCoastal?: boolean;
      minBuildings?: number;
      requiresMissingBuilding?: string[];
    }
  | { kind: 'perBuildingCategory'; category: BuildingCategory; yields: Partial<ResourceYield> }
  | { kind: 'perBuildingId'; buildingIds: string[]; yields: Partial<ResourceYield> }
  | { kind: 'perImprovement'; improvement: ImprovementType; yields: Partial<ResourceYield> }
  | { kind: 'perPopulation'; per: number; yields: Partial<ResourceYield> }
  | { kind: 'empirePercent'; resource: keyof ResourceYield | 'all'; percent: number }
  | { kind: 'perTradeRoute'; gold: number; foreignOnly?: boolean; coastalOnly?: boolean }
  | { kind: 'perLuxuryResource'; gold: number }
  | { kind: 'perOwnedNaturalWonder'; science: number }
  | { kind: 'foundingBonus'; food: number }
  /** Flat bonus applied once to the civ's totals — not per city (see MR6 "empire-wide" rule). */
  | { kind: 'empireFlat'; yields: Partial<ResourceYield> }
  /** Applied per worked tile whose terrain matches, resolved in tile-yield.ts. */
  | { kind: 'terrainYield'; terrains: TerrainType[]; yields: Partial<ResourceYield> }
  | { kind: 'perCompletedLegendaryWonder'; gold: number }
  /** Distinct foreign civs with an active peacetime trade route to this civ. */
  | { kind: 'perRoutePartnerCiv'; gold: number }
  /** Gold per active route (sent or received) in cities with the required building. */
  | { kind: 'perCityRoute'; requiresBuilding: string; gold: number }
  /** +science to the civ's single lowest-science city (deterministic tiebreak by city id). */
  | { kind: 'lowestCityScience'; science: number }
  /** +food per N science generated by the same city that turn (pre-bonus science). */
  | { kind: 'foodFromScience'; perScience: number }
  /** Building-upkeep multiplier in cities meeting minBuildings. */
  | { kind: 'maintenanceDiscount'; minBuildings: number; multiplier: number }
  /** Percent bonus applied to trade-route gold only (distinct from empirePercent). */
  | { kind: 'tradeRoutePercent'; percent: number };

export interface TechYieldModifier {
  techId: string;
  label: string;
  effect: YieldKind;
}

export const TECH_YIELD_MODIFIERS: TechYieldModifier[] = [
  // --- Era 5 ---
  { techId: 'guilds', label: '+1 gold per active trade route', effect: { kind: 'perTradeRoute', gold: 1 } },
  { techId: 'colonial-trade', label: 'Trade routes to foreign civs yield +2 gold', effect: { kind: 'perTradeRoute', gold: 2, foreignOnly: true } },
  { techId: 'scientific-method', label: '+1 science per library empire-wide', effect: { kind: 'perBuildingId', buildingIds: ['library'], yields: { science: 1 } } },
  { techId: 'printing-press', label: '+1 science per library empire-wide', effect: { kind: 'perBuildingId', buildingIds: ['library'], yields: { science: 1 } } },
  { techId: 'civic-humanism', label: '+5% gold empire-wide', effect: { kind: 'empirePercent', resource: 'gold', percent: 5 } },
  { techId: 'empiricism', label: '+1 science all cities', effect: { kind: 'cityFlat', yields: { science: 1 } } },
  { techId: 'rationalism', label: '+5% science empire-wide', effect: { kind: 'empirePercent', resource: 'science', percent: 5 } },
  { techId: 'renaissance-painting', label: '+1 gold per culture building empire-wide', effect: { kind: 'perBuildingCategory', category: 'culture', yields: { gold: 1 } } },
  { techId: 'classical-music-form', label: '+1 science per culture building empire-wide', effect: { kind: 'perBuildingCategory', category: 'culture', yields: { science: 1 } } },
  { techId: 'deep-sea-routes', label: '+1 gold per coastal city', effect: { kind: 'cityFlatConditional', requiresCoastal: true, yields: { gold: 1 } } },
  { techId: 'blast-furnace-tech', label: '+1 production all cities', effect: { kind: 'cityFlat', yields: { production: 1 } } },
  { techId: 'distillation', label: '+2 gold per owned luxury resource', effect: { kind: 'perLuxuryResource', gold: 2 } },
  { techId: 'plantation-farming', label: 'Farms yield +1 food', effect: { kind: 'perImprovement', improvement: 'farm', yields: { food: 1 } } },
  { techId: 'monastic-orders', label: '+1 science and +1 gold per city with temple', effect: { kind: 'cityFlatConditional', requiresAnyBuilding: ['temple'], yields: { science: 1, gold: 1 } } },
  { techId: 'reformation', label: '+2 science in cities with a temple', effect: { kind: 'cityFlatConditional', requiresAnyBuilding: ['temple'], yields: { science: 2 } } },
  // postal-service: '+1 gold per road tile in your territory (max +10)' — resolved by getRoadTileTechGold (needs the owned-road-tile count, not table-drivable).

  // --- Era 6 ---
  { techId: 'mercantilism', label: '+5% gold empire-wide', effect: { kind: 'empirePercent', resource: 'gold', percent: 5 } },
  { techId: 'natural-history', label: '+2 science per natural wonder in empire territory', effect: { kind: 'perOwnedNaturalWonder', science: 2 } },
  { techId: 'hydraulics', label: '+2 production in river cities', effect: { kind: 'cityFlatConditional', requiresRiver: true, yields: { production: 2 } } },
  { techId: 'separation-of-powers', label: '+1 gold per culture building empire-wide', effect: { kind: 'perBuildingCategory', category: 'culture', yields: { gold: 1 } } },
  { techId: 'parliamentary-reform', label: '+5% production empire-wide', effect: { kind: 'empirePercent', resource: 'production', percent: 5 } },
  { techId: 'land-survey', label: '+1 food in all cities empire-wide', effect: { kind: 'cityFlat', yields: { food: 1 } } },
  { techId: 'improved-agriculture', label: 'Farms yield +1 food', effect: { kind: 'perImprovement', improvement: 'farm', yields: { food: 1 } } },
  { techId: 'improved-agriculture', label: 'Granaries add +1 food', effect: { kind: 'perBuildingId', buildingIds: ['granary'], yields: { food: 1 } } },
  { techId: 'tobacco-trade', label: '+2 gold per plantation improvement', effect: { kind: 'perImprovement', improvement: 'plantation', yields: { gold: 2 } } },
  { techId: 'enlightenment', label: '+1 science per two population in cities', effect: { kind: 'perPopulation', per: 2, yields: { science: 1 } } },
  { techId: 'social-contract', label: '+2 gold per city with a market', effect: { kind: 'cityFlatConditional', requiresAnyBuilding: ['marketplace'], yields: { gold: 2 } } },
  { techId: 'baroque-music', label: '+1 gold per culture building', effect: { kind: 'perBuildingCategory', category: 'culture', yields: { gold: 1 } } },
  { techId: 'portrait-art', label: '+1 gold per art gallery in empire', effect: { kind: 'perBuildingId', buildingIds: ['art_gallery'], yields: { gold: 1 } } },
  { techId: 'aqueduct-expansion', label: '+2 food in all cities with aqueduct', effect: { kind: 'cityFlatConditional', requiresAnyBuilding: ['aqueduct'], yields: { food: 2 } } },
  { techId: 'newspaper-press', label: '+2 science empire-wide', effect: { kind: 'cityFlat', yields: { science: 2 } } },
  { techId: 'ecumenical-council', label: '+2 gold per city with a temple empire-wide', effect: { kind: 'cityFlatConditional', requiresAnyBuilding: ['temple'], yields: { gold: 2 } } },
  // courier-network / colonial-railways / transcontinental-rail: resolved by getConnectedCityTechGold (needs road-BFS connectivity, not table-drivable).

  // --- Era 7 ---
  { techId: 'mass-production', label: '+10% production empire-wide', effect: { kind: 'empirePercent', resource: 'production', percent: 10 } },
  { techId: 'industrialization', label: '+2 science empire-wide', effect: { kind: 'cityFlat', yields: { science: 2 } } },
  { techId: 'applied-chemistry', label: '+1 science per production building empire-wide', effect: { kind: 'perBuildingCategory', category: 'production', yields: { science: 1 } } },
  { techId: 'social-reform', label: '+1 gold in cities with a market or guildhall', effect: { kind: 'cityFlatConditional', requiresAnyBuilding: ['marketplace', 'guildhall'], yields: { gold: 1 } } },
  { techId: 'manifest-destiny', label: 'New cities founded with +5 food bonus', effect: { kind: 'foundingBonus', food: 5 } },
  { techId: 'mechanized-farming', label: 'Farms yield +1 production in addition to food', effect: { kind: 'perImprovement', improvement: 'farm', yields: { production: 1 } } },
  { techId: 'mechanized-farming', label: 'Granaries add +1 additional food', effect: { kind: 'perBuildingId', buildingIds: ['granary'], yields: { food: 1 } } },
  { techId: 'agricultural-machinery', label: '+2 food per farm improvement', effect: { kind: 'perImprovement', improvement: 'farm', yields: { food: 2 } } },
  { techId: 'utilitarianism', label: '+1 gold per 3 population empire-wide', effect: { kind: 'perPopulation', per: 3, yields: { gold: 1 } } },
  { techId: 'positivism', label: '+2 science empire-wide', effect: { kind: 'cityFlat', yields: { science: 2 } } },
  { techId: 'positivism', label: 'Universities generate +1 additional science', effect: { kind: 'perBuildingId', buildingIds: ['university'], yields: { science: 1 } } },
  { techId: 'romanticism', label: 'Culture buildings generate +1 gold and +1 science', effect: { kind: 'perBuildingCategory', category: 'culture', yields: { gold: 1, science: 1 } } },
  { techId: 'industrial-realism', label: 'Culture buildings generate +1 production', effect: { kind: 'perBuildingCategory', category: 'culture', yields: { production: 1 } } },
  { techId: 'steam-navigation', label: 'Naval trade routes yield +2 gold', effect: { kind: 'perTradeRoute', gold: 2, coastalOnly: true } },
  { techId: 'steam-navigation', label: 'Coastal cities gain +1 production from harbours', effect: { kind: 'cityFlatConditional', requiresCoastal: true, requiresAnyBuilding: ['harbor'], yields: { production: 1 } } },
  { techId: 'urban-planning', label: '+2 production in cities with 3 or more buildings', effect: { kind: 'cityFlatConditional', minBuildings: 3, yields: { production: 2 } } },
  { techId: 'iron-bridges', label: '+1 gold per river city', effect: { kind: 'cityFlatConditional', requiresRiver: true, yields: { gold: 1 } } },
  { techId: 'secularism', label: '+2 science in cities without a temple', effect: { kind: 'cityFlatConditional', requiresMissingBuilding: ['temple'], yields: { science: 2 } } },
  { techId: 'social-gospel', label: '+1 food and +1 gold in cities with a temple', effect: { kind: 'cityFlatConditional', requiresAnyBuilding: ['temple'], yields: { food: 1, gold: 1 } } },
  // germ-theory: healing — owned by MR4

  // --- Era 8 ---
  { techId: 'finance-capitalism', label: 'Trade route gold +25%', effect: { kind: 'tradeRoutePercent', percent: 25 } },
  { techId: 'industrial-monopoly', label: '+2 gold per city with a market', effect: { kind: 'cityFlatConditional', requiresAnyBuilding: ['marketplace'], yields: { gold: 2 } } },
  // Re-text: "heal faster with medical buildings" has no healing-tech hook here — implemented as +1 food per city with a bacteriology lab.
  { techId: 'germ-biology', label: '+1 food per city with a bacteriology lab', effect: { kind: 'cityFlatConditional', requiresAnyBuilding: ['bacteriology_lab'], yields: { food: 1 } } },
  { techId: 'engineering-exhibition', label: '+1 science empire-wide', effect: { kind: 'cityFlat', yields: { science: 1 } } },
  // Re-text: happiness bonus has no unrest hook here — implemented as +1 food per city with a marketplace.
  { techId: 'labor-rights', label: '+1 food per city with a marketplace', effect: { kind: 'cityFlatConditional', requiresAnyBuilding: ['marketplace'], yields: { food: 1 } } },
  { techId: 'public-records', label: '+1 science empire-wide', effect: { kind: 'cityFlat', yields: { science: 1 } } },
  // Re-text: drop the spoilage-elimination clause — spoilage events don't exist.
  { techId: 'refrigeration', label: '+2 food all cities', effect: { kind: 'cityFlat', yields: { food: 2 } } },
  { techId: 'scientific-breeding', label: '+1 food per farm improvement', effect: { kind: 'perImprovement', improvement: 'farm', yields: { food: 1 } } },
  // Re-text: "granary bonus doubled" made explicit as a flat +1 food per granary.
  { techId: 'scientific-breeding', label: '+1 food per granary', effect: { kind: 'perBuildingId', buildingIds: ['granary'], yields: { food: 1 } } },
  { techId: 'pragmatism', label: '+5% to all city yields', effect: { kind: 'empirePercent', resource: 'all', percent: 5 } },
  { techId: 'dialectical-materialism', label: '+2 science in cities with a library', effect: { kind: 'cityFlatConditional', requiresAnyBuilding: ['library'], yields: { science: 2 } } },
  { techId: 'impressionism', label: 'Culture buildings generate +1 gold and +1 science', effect: { kind: 'perBuildingCategory', category: 'culture', yields: { gold: 1, science: 1 } } },
  { techId: 'grand-opera', label: '+2 gold empire-wide', effect: { kind: 'cityFlat', yields: { gold: 2 } } },
  { techId: 'sanitation-networks', label: '+1 food all cities', effect: { kind: 'cityFlat', yields: { food: 1 } } },
  { techId: 'bessemer-steel', label: '+2 production in cities with a blast furnace', effect: { kind: 'cityFlatConditional', requiresAnyBuilding: ['blast_furnace'], yields: { production: 2 } } },
  // Re-text: "per construction building" -> production-category buildings.
  { techId: 'structural-engineering', label: '+1 production per production building empire-wide', effect: { kind: 'perBuildingCategory', category: 'production', yields: { production: 1 } } },
  { techId: 'reinforced-concrete', label: '+2 production in cities with 4 or more buildings', effect: { kind: 'cityFlatConditional', minBuildings: 4, yields: { production: 2 } } },
  { techId: 'shorthand-press', label: '+1 science and +1 gold per city', effect: { kind: 'cityFlat', yields: { science: 1, gold: 1 } } },
  { techId: 'modernist-theology', label: '+2 science in cities with a temple or monastery', effect: { kind: 'cityFlatConditional', requiresAnyBuilding: ['temple', 'monastery'], yields: { science: 2 } } },
  // "Religion building" = temple or monastery.
  { techId: 'social-justice', label: '+1 food and +1 gold per city with a religion building', effect: { kind: 'cityFlatConditional', requiresAnyBuilding: ['temple', 'monastery'], yields: { food: 1, gold: 1 } } },

  // --- Era 9 ---
  { techId: 'universal-suffrage', label: '+1 food all cities', effect: { kind: 'cityFlat', yields: { food: 1 } } },
  { techId: 'quantum-theory', label: '+2 science all cities', effect: { kind: 'cityFlat', yields: { science: 2 } } },
  { techId: 'chemical-fertilizers', label: '+2 food per farm improvement', effect: { kind: 'perImprovement', improvement: 'farm', yields: { food: 2 } } },
  { techId: 'large-scale-irrigation', label: '+1 food all cities', effect: { kind: 'cityFlat', yields: { food: 1 } } },
  { techId: 'modern-psychiatry', label: '+1 food in cities with a sanatorium', effect: { kind: 'cityFlatConditional', requiresAnyBuilding: ['sanatorium'], yields: { food: 1 } } },
  { techId: 'pragmatic-empiricism', label: '+2 science in cities with a library', effect: { kind: 'cityFlatConditional', requiresAnyBuilding: ['library'], yields: { science: 2 } } },
  { techId: 'existentialism', label: '+1 gold per culture building empire-wide', effect: { kind: 'perBuildingCategory', category: 'culture', yields: { gold: 1 } } },
  { techId: 'jazz-age', label: '+2 gold in cities with an opera house', effect: { kind: 'cityFlatConditional', requiresAnyBuilding: ['opera_house'], yields: { gold: 2 } } },
  { techId: 'convoy-system', label: '+2 gold per trade route empire-wide', effect: { kind: 'perTradeRoute', gold: 2 } },
  { techId: 'aluminium-smelting', label: '+1 production all cities', effect: { kind: 'cityFlat', yields: { production: 1 } } },
  { techId: 'steel-skyscrapers', label: '+2 production in cities with 6 or more buildings', effect: { kind: 'cityFlatConditional', minBuildings: 6, yields: { production: 2 } } },
  { techId: 'wireless-telegraph', label: '+2 gold empire-wide', effect: { kind: 'empireFlat', yields: { gold: 2 } } },
  { techId: 'propaganda-campaigns', label: '+2 gold in cities with a film studio or radio station', effect: { kind: 'cityFlatConditional', requiresAnyBuilding: ['film_studio', 'radio_station'], yields: { gold: 2 } } },
  { techId: 'religious-modernism', label: '+1 science in cities with a religion building', effect: { kind: 'cityFlatConditional', requiresAnyBuilding: ['temple', 'monastery'], yields: { science: 1 } } },
  { techId: 'secular-humanism', label: '+1 food all cities', effect: { kind: 'cityFlat', yields: { food: 1 } } },
  { techId: 'hydroelectric-power', label: '+2 production in river cities', effect: { kind: 'cityFlatConditional', requiresRiver: true, yields: { production: 2 } } },

  // --- Era 10 ---
  { techId: 'keynesian-economics', label: '+2 gold all cities', effect: { kind: 'cityFlat', yields: { gold: 2 } } },
  { techId: 'consumer-boom', label: '+2 gold in cities with a market', effect: { kind: 'cityFlatConditional', requiresAnyBuilding: ['marketplace'], yields: { gold: 2 } } },
  { techId: 'nuclear-physics', label: '+3 science in cities with a research institute', effect: { kind: 'cityFlatConditional', requiresAnyBuilding: ['research_institute'], yields: { science: 3 } } },
  { techId: 'radar-systems', label: '+2 science empire-wide', effect: { kind: 'cityFlat', yields: { science: 2 } } },
  // "Empire-wide" texts without "per/all cities" resolve to a single flat civ-total bonus (empireFlat), not per-city.
  { techId: 'decolonization', label: '+2 gold empire-wide', effect: { kind: 'empireFlat', yields: { gold: 2 } } },
  { techId: 'international-institutions', label: '+1 gold and +1 science empire-wide', effect: { kind: 'empireFlat', yields: { gold: 1, science: 1 } } },
  { techId: 'rocketry', label: '+2 science in cities with a research institute', effect: { kind: 'cityFlatConditional', requiresAnyBuilding: ['research_institute'], yields: { science: 2 } } },
  { techId: 'polar-operations', label: '+1 food and +1 production in tundra and snow tiles', effect: { kind: 'terrainYield', terrains: ['tundra', 'snow'], yields: { food: 1, production: 1 } } },
  { techId: 'pesticides', label: '+1 food per farm improvement', effect: { kind: 'perImprovement', improvement: 'farm', yields: { food: 1 } } },
  { techId: 'mechanized-agriculture', label: '+2 production in cities with a granary', effect: { kind: 'cityFlatConditional', requiresAnyBuilding: ['granary'], yields: { production: 2 } } },
  { techId: 'universal-healthcare', label: '+2 food all cities', effect: { kind: 'cityFlat', yields: { food: 2 } } },
  { techId: 'post-colonial-theory', label: '+1 science all cities', effect: { kind: 'cityFlat', yields: { science: 1 } } },
  { techId: 'human-rights-framework', label: '+1 gold all cities', effect: { kind: 'cityFlat', yields: { gold: 1 } } },
  { techId: 'abstract-expressionism', label: '+2 gold in cities with an art gallery', effect: { kind: 'cityFlatConditional', requiresAnyBuilding: ['art_gallery'], yields: { gold: 2 } } },
  // Re-text: "music hall" -> concert hall (the actual culture building).
  { techId: 'rock-and-roll', label: '+2 gold in cities with a concert hall', effect: { kind: 'cityFlatConditional', requiresAnyBuilding: ['concert_hall'], yields: { gold: 2 } } },
  { techId: 'titanium-processing', label: '+2 production in cities with a factory', effect: { kind: 'cityFlatConditional', requiresAnyBuilding: ['factory'], yields: { production: 2 } } },
  { techId: 'synthetic-polymers', label: '+1 production all cities', effect: { kind: 'cityFlat', yields: { production: 1 } } },
  // nuclear-power: re-text drops the stale "+4" — the nuclear power plant building already yields +5. No tech-level entry.
  { techId: 'television', label: '+2 gold in cities with a film studio or radio station', effect: { kind: 'cityFlatConditional', requiresAnyBuilding: ['film_studio', 'radio_station'], yields: { gold: 2 } } },
  { techId: 'electronic-computing', label: '+3 science in cities with a research institute', effect: { kind: 'cityFlatConditional', requiresAnyBuilding: ['research_institute'], yields: { science: 3 } } },
  { techId: 'liberation-theology', label: '+1 food in cities with a temple', effect: { kind: 'cityFlatConditional', requiresAnyBuilding: ['temple'], yields: { food: 1 } } },
  { techId: 'interfaith-council', label: '+1 science in cities with a religion building', effect: { kind: 'cityFlatConditional', requiresAnyBuilding: ['temple', 'monastery'], yields: { science: 1 } } },
  // highway-network has no road-tile dependency ("+2 gold empire-wide" as written) — grouped here with the other road-family effects.
  { techId: 'highway-network', label: '+2 gold empire-wide', effect: { kind: 'empireFlat', yields: { gold: 2 } } },

  // --- Era 11 ---
  { techId: 'stagflation-response', label: '+3 gold all cities', effect: { kind: 'cityFlat', yields: { gold: 3 } } },
  { techId: 'petrodollar-system', label: '+2 gold per trade route empire-wide', effect: { kind: 'perTradeRoute', gold: 2 } },
  { techId: 'integrated-circuits', label: '+3 science in cities with a research institute', effect: { kind: 'cityFlatConditional', requiresAnyBuilding: ['research_institute'], yields: { science: 3 } } },
  { techId: 'molecular-biology', label: '+2 science empire-wide', effect: { kind: 'cityFlat', yields: { science: 2 } } },
  { techId: 'arms-control-negotiations', label: '+2 gold empire-wide', effect: { kind: 'empireFlat', yields: { gold: 2 } } },
  { techId: 'civil-rights-legislation', label: '+2 food all cities', effect: { kind: 'cityFlat', yields: { food: 2 } } },
  { techId: 'deep-sea-drilling', label: '+1 food and +2 gold empire-wide', effect: { kind: 'empireFlat', yields: { food: 1, gold: 2 } } },
  { techId: 'green-revolution-crops', label: '+2 food per farm improvement', effect: { kind: 'perImprovement', improvement: 'farm', yields: { food: 2 } } },
  { techId: 'aquaculture', label: '+2 food all cities', effect: { kind: 'cityFlat', yields: { food: 2 } } },
  { techId: 'vaccination-campaigns', label: '+2 food all cities', effect: { kind: 'cityFlat', yields: { food: 2 } } },
  { techId: 'structuralism', label: '+2 science empire-wide', effect: { kind: 'empireFlat', yields: { science: 2 } } },
  // Re-text: "per arts building" -> culture-category buildings (arts is a tech track, not a building category).
  { techId: 'postmodernism', label: '+1 gold per culture building empire-wide', effect: { kind: 'perBuildingCategory', category: 'culture', yields: { gold: 1 } } },
  { techId: 'pop-art', label: '+2 gold in cities with an art gallery', effect: { kind: 'cityFlatConditional', requiresAnyBuilding: ['art_gallery'], yields: { gold: 2 } } },
  // Re-text: "music hall" -> concert hall.
  { techId: 'counterculture', label: '+2 gold in cities with a concert hall', effect: { kind: 'cityFlatConditional', requiresAnyBuilding: ['concert_hall'], yields: { gold: 2 } } },
  { techId: 'precision-engineering', label: '+2 production in cities with a factory', effect: { kind: 'cityFlatConditional', requiresAnyBuilding: ['factory'], yields: { production: 2 } } },
  { techId: 'megastructures', label: '+2 production all cities', effect: { kind: 'cityFlat', yields: { production: 2 } } },
  { techId: 'offshore-platforms', label: '+2 gold and +1 production empire-wide', effect: { kind: 'empireFlat', yields: { gold: 2, production: 1 } } },
  { techId: 'satellite-television', label: '+2 gold in cities with a film studio or radio station', effect: { kind: 'cityFlatConditional', requiresAnyBuilding: ['film_studio', 'radio_station'], yields: { gold: 2 } } },
  { techId: 'black-ops-programs', label: '+2 gold empire-wide', effect: { kind: 'empireFlat', yields: { gold: 2 } } },
  { techId: 'ecumenical-movement', label: '+1 science and +1 food empire-wide', effect: { kind: 'empireFlat', yields: { science: 1, food: 1 } } },
  // Re-text: "temple or mosque" -> temple or monastery (no mosque building exists).
  { techId: 'new-age-spirituality', label: '+2 gold in cities with a temple or monastery', effect: { kind: 'cityFlatConditional', requiresAnyBuilding: ['temple', 'monastery'], yields: { gold: 2 } } },

  // --- Era 12 ---
  { techId: 'digital-rights', label: '+1 science per espionage building empire-wide', effect: { kind: 'perBuildingCategory', category: 'espionage', yields: { science: 1 } } },
  // network-governance: resolved by getLowestScienceCityBonus in tech-yield-system.ts (needs cross-city context this table can't express).
  { techId: 'network-governance', label: '+2 science to your lowest-science city', effect: { kind: 'lowestCityScience', science: 2 } },
  // Re-text: no 'civics' building category exists -> +1 science per culture building.
  { techId: 'secular-rationalism', label: '+1 science per culture building empire-wide', effect: { kind: 'perBuildingCategory', category: 'culture', yields: { science: 1 } } },
  { techId: 'new-secularism', label: '+1 gold per science building empire-wide', effect: { kind: 'perBuildingCategory', category: 'science', yields: { gold: 1 } } },
  { techId: 'digital-art', label: '+1 gold per legendary wonder you control', effect: { kind: 'perCompletedLegendaryWonder', gold: 1 } },
  // Re-text: no 'entertainment' building category -> +2 gold per culture building.
  { techId: 'video-games', label: '+2 gold per culture building empire-wide', effect: { kind: 'perBuildingCategory', category: 'culture', yields: { gold: 2 } } },
  { techId: 'globalization', label: '+1 gold per distinct peacetime trade-route partner civilization', effect: { kind: 'perRoutePartnerCiv', gold: 1 } },
  { techId: 'digital-economy', label: '+1 gold per active trade route in cities with a fintech hub', effect: { kind: 'perCityRoute', requiresBuilding: 'fintech_hub', gold: 1 } },
  // deep-ocean-research: +1 trade-route capacity for coastal cities — resolved in trade-system.ts getRouteCapacity, no yield entry.
  // Re-text: trade routes have no maintenance to remove -> +1 gold per active trade route.
  { techId: 'autonomous-shipping', label: '+1 gold per active trade route', effect: { kind: 'perTradeRoute', gold: 1 } },
  // Re-text: naval blockades don't exist -> flat food bonus.
  { techId: 'lab-grown-food', label: '+2 food all cities', effect: { kind: 'cityFlat', yields: { food: 2 } } },
  // green-architecture: resolved by getMaintenanceDiscountMultiplier in economy-system.ts (building-upkeep math, not a yield).
  { techId: 'green-architecture', label: '-10% building maintenance in cities with 6 or more buildings', effect: { kind: 'maintenanceDiscount', minBuildings: 6, multiplier: 0.9 } },
  { techId: 'smart-cities', label: '+2 production and +1 science with a factory and semiconductor fab', effect: { kind: 'cityFlatConditional', requiresAllBuildings: ['factory', 'semiconductor_fab'], yields: { production: 2, science: 1 } } },
  // genomics: resolved directly in resource-system.ts calculateCityYields (needs the city's own pre-empire-percent science total).
  { techId: 'genomics', label: '+1 food per 3 science generated per turn (pre-bonus)', effect: { kind: 'foodFromScience', perScience: 3 } },
  // gps-navigation: movement/terrain-cost effect — deferred to MR7 (movement systems live in unit-system, not the yield engine).
];

export interface TechCostDiscount {
  techId: string;
  appliesTo: 'buildings' | 'units' | UnitType[];
  multiplier: number;
}

export const TECH_COST_DISCOUNTS: TechCostDiscount[] = [
  { techId: 'vaulted-ceilings', appliesTo: 'buildings', multiplier: 0.90 },
  { techId: 'cannon-casting', appliesTo: ['cannon'], multiplier: 0.85 },
  { techId: 'mass-production', appliesTo: 'units', multiplier: 0.95 },
  { techId: 'manifest-destiny', appliesTo: ['settler'], multiplier: 0.80 },
];

/** Food bonus applied once at city-founding time (not a per-turn yield). */
export function getFoundingBonusFood(completedTechs: string[]): number {
  const techSet = new Set(completedTechs);
  let bonus = 0;

  for (const modifier of TECH_YIELD_MODIFIERS) {
    if (modifier.effect.kind !== 'foundingBonus') continue;
    if (!techSet.has(modifier.techId)) continue;
    bonus += modifier.effect.food;
  }

  return bonus;
}
