import type { WonderDefinition } from '@/core/types';

export const WONDER_DEFINITIONS: WonderDefinition[] = [
  {
    id: 'great_volcano',
    name: 'Great Volcano',
    description: 'A massive volcano that occasionally erupts, destroying nearby improvements.',
    yields: { food: 0, production: 3, gold: 0, science: 1 },
    discoveryBonus: { type: 'science', amount: 30 },
    effect: { type: 'eruption', chance: 0.05 },
    validTerrain: ['volcanic'],
  },
  {
    id: 'sacred_mountain',
    name: 'Sacred Mountain',
    description: 'A holy peak that inspires scholars in adjacent tiles.',
    yields: { food: 0, production: 0, gold: 2, science: 2 },
    discoveryBonus: { type: 'science', amount: 25 },
    effect: { type: 'adjacent_yield_bonus', yields: { science: 1 } },
    validTerrain: ['mountain'],
  },
  {
    id: 'crystal_caverns',
    name: 'Crystal Caverns',
    description: 'Caves filled with precious crystals and rare minerals.',
    yields: { food: 0, production: 1, gold: 3, science: 0 },
    discoveryBonus: { type: 'gold', amount: 50 },
    effect: { type: 'none' },
    validTerrain: ['hills'],
  },
  {
    id: 'ancient_forest',
    name: 'Ancient Forest',
    description: 'A primeval forest with healing properties.',
    yields: { food: 2, production: 1, gold: 0, science: 0 },
    discoveryBonus: { type: 'production', amount: 20 },
    effect: { type: 'healing', hpPerTurn: 10 },
    validTerrain: ['forest'],
  },
  {
    id: 'coral_reef',
    name: 'Coral Reef',
    description: 'A vibrant reef teeming with sea life.',
    yields: { food: 2, production: 0, gold: 1, science: 0 },
    discoveryBonus: { type: 'gold', amount: 30 },
    effect: { type: 'adjacent_yield_bonus', yields: { food: 1 } },
    validTerrain: ['coast'],
  },
  {
    id: 'grand_canyon',
    name: 'Grand Canyon',
    description: 'A vast canyon providing natural fortification.',
    yields: { food: 0, production: 0, gold: 2, science: 1 },
    discoveryBonus: { type: 'gold', amount: 25 },
    effect: { type: 'combat_bonus', defenseBonus: 0.30 },
    validTerrain: ['desert'],
  },
  {
    id: 'aurora_fields',
    name: 'Aurora Fields',
    description: 'Frozen plains illuminated by dancing lights.',
    yields: { food: 1, production: 0, gold: 0, science: 3 },
    discoveryBonus: { type: 'science', amount: 40 },
    effect: { type: 'none' },
    validTerrain: ['tundra'],
  },
  {
    id: 'frozen_falls',
    name: 'Frozen Falls',
    description: 'An immense frozen waterfall with a commanding view.',
    yields: { food: 0, production: 2, gold: 1, science: 1 },
    discoveryBonus: { type: 'production', amount: 20 },
    effect: { type: 'vision', bonus: 2 },
    validTerrain: ['snow'],
  },
  {
    id: 'dragon_bones',
    name: 'Dragon Bones',
    description: 'Ancient skeletal remains of a massive creature.',
    yields: { food: 0, production: 2, gold: 0, science: 2 },
    discoveryBonus: { type: 'science', amount: 35 },
    effect: { type: 'combat_bonus', defenseBonus: 0.20 },
    validTerrain: ['plains'],
  },
  {
    id: 'singing_sands',
    name: 'Singing Sands',
    description: 'Dunes that hum with an eerie melody.',
    yields: { food: 1, production: 0, gold: 2, science: 0 },
    discoveryBonus: { type: 'gold', amount: 30 },
    effect: { type: 'none' },
    validTerrain: ['desert'],
  },
  {
    id: 'sunken_ruins',
    name: 'Sunken Ruins',
    description: 'Remnants of a lost civilization beneath the waves.',
    yields: { food: 0, production: 0, gold: 2, science: 2 },
    discoveryBonus: { type: 'science', amount: 40 },
    effect: { type: 'none' },
    validTerrain: ['coast'],
  },
  {
    id: 'floating_islands',
    name: 'Floating Islands',
    description: 'Rocky outcrops that seem to defy gravity.',
    yields: { food: 1, production: 1, gold: 1, science: 1 },
    discoveryBonus: { type: 'production', amount: 25 },
    effect: { type: 'vision', bonus: 1 },
    validTerrain: ['hills'],
  },
  {
    id: 'bioluminescent_bay',
    name: 'Bioluminescent Bay',
    description: 'A bay that glows with otherworldly light.',
    yields: { food: 1, production: 0, gold: 2, science: 1 },
    discoveryBonus: { type: 'gold', amount: 35 },
    effect: { type: 'adjacent_yield_bonus', yields: { gold: 1 } },
    validTerrain: ['coast'],
  },
  {
    id: 'bottomless_lake',
    name: 'Bottomless Lake',
    description: 'A mysterious lake with restorative waters.',
    yields: { food: 0, production: 1, gold: 1, science: 2 },
    discoveryBonus: { type: 'science', amount: 30 },
    effect: { type: 'healing', hpPerTurn: 5 },
    validTerrain: ['swamp'],
  },
  {
    id: 'eternal_storm',
    name: 'Eternal Storm',
    description: 'A perpetual tempest over open waters granting far sight.',
    yields: { food: 0, production: 0, gold: 0, science: 3 },
    discoveryBonus: { type: 'science', amount: 50 },
    effect: { type: 'vision', bonus: 3 },
    validTerrain: ['ocean'],
  },
];

export function getWonderDefinition(id: string): WonderDefinition | undefined {
  return WONDER_DEFINITIONS.find(w => w.id === id);
}
