#!/usr/bin/env bash
set -euo pipefail

# #612: objective audio validation for every cue scripts/generate-unit-sfx.sh produces.
# Needs ffmpeg/ffprobe (the vitest suite deliberately does not).
#
#   scripts/validate-unit-sfx.sh                     validate, exit 1 on any failure
#   scripts/validate-unit-sfx.sh --write-manifest    also rewrite docs/audio/unit-sfx-manifest.md
#
# Policy (same numbers the generator enforces):
#   decodes cleanly · mono 44.1 kHz Vorbis · no metadata tags · true peak <= -1.0 dBTP · no clipping ·
#   not silent (RMS above -45 dB) · >= 0.1 s · integrated loudness <= -16 LUFS when measurable (>= 400 ms)

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SFX="$ROOT/public/audio/sfx"
MANIFEST="$ROOT/docs/audio/unit-sfx-manifest.md"
WRITE=0; [[ "${1:-}" == "--write-manifest" ]] && WRITE=1

names=()
while IFS= read -r line; do names+=("$line"); done < <(awk '/^finish [a-z0-9-]+ /{print $2}' "$ROOT/scripts/generate-unit-sfx.sh")
[[ ${#names[@]} -gt 0 ]] || { echo "no cues found in generate-unit-sfx.sh" >&2; exit 1; }

failures=0
rows=()
for name in "${names[@]}"; do
  f="$SFX/$name.ogg"
  fail() { printf 'FAIL %-22s %s\n' "$name" "$1" >&2; failures=$((failures + 1)); }
  [[ -f "$f" ]] || { fail "missing file"; continue; }

  ffmpeg -v error -i "$f" -f null - 2>"$ROOT/.validate-unit-sfx.err" || true
  [[ ! -s "$ROOT/.validate-unit-sfx.err" ]] || fail "decode errors: $(head -1 "$ROOT/.validate-unit-sfx.err")"
  rm -f "$ROOT/.validate-unit-sfx.err"

  codec="$(ffprobe -v error -select_streams a:0 -show_entries stream=codec_name,sample_rate,channels -of csv=p=0 "$f")"
  [[ "$codec" == "vorbis,44100,1" ]] || fail "expected vorbis,44100,1 got $codec"
  [[ -z "$(ffprobe -v error -show_entries format_tags:stream_tags -of csv=p=0 "$f")" ]] || fail "metadata tags present"

  dur="$(ffprobe -v error -show_entries format=duration -of csv=p=0 "$f")"
  awk -v d="$dur" 'BEGIN { exit !(d >= 0.1) }' || fail "duration $dur s < 0.1 s"

  stats="$(ffmpeg -hide_banner -nostats -i "$f" -af astats=metadata=0 -f null - 2>&1)"
  rms="$(awk '/Overall/{o=1} o&&/RMS level dB/{sub(/.*: /,""); print; exit}' <<<"$stats")"
  samplepeak="$(awk '/Overall/{o=1} o&&/Peak level dB/{sub(/.*: /,""); print; exit}' <<<"$stats")"
  awk -v r="$rms" 'BEGIN { exit !(r > -45) }' || fail "looks silent (RMS $rms dB)"
  awk -v p="$samplepeak" 'BEGIN { exit !(p < -0.1) }' || fail "clipping (sample peak $samplepeak dB)"

  e="$(ffmpeg -hide_banner -nostats -i "$f" -af ebur128=peak=true -f null - 2>&1)"
  lufs="$(awk '/^ +I:/{print $2}' <<<"$e" | tail -1)"
  tp="$(awk '/^ +Peak:/{print $2}' <<<"$e" | tail -1)"
  awk -v t="$tp" 'BEGIN { exit !(t <= -1.0) }' || fail "true peak $tp dBTP > -1.0"
  # EBU R128 needs a full 400 ms gating block; ebur128 reports its -70 floor for anything shorter or quieter.
  if awk -v d="$dur" -v l="$lufs" 'BEGIN { exit !(d >= 0.4 && l > -69) }'; then
    awk -v l="$lufs" 'BEGIN { exit !(l <= -16.0) }' || fail "integrated $lufs LUFS > -16"
  else
    lufs="n/a (<400 ms gate)"
  fi

  # Source files named by this cue's recipe in generate-unit-sfx.sh (FIRE/NAV/RTS = the three CC0 sets).
  src="$(awk -v n="$name" '$1=="finish"{on=($2==n)} on' "$ROOT/scripts/generate-unit-sfx.sh" \
    | { grep -oE -- '-i "\$(FIRE|NAV|RTS|VOICE|PROP|JET)(/[^"]+)?"' || true; } | sed -E 's/-i "\$//; s/"$//' | sed -E 's#^FIRE/#firearms: #; s#^NAV/#naval: #; s#^RTS/#rts: #; s#^VOICE/#voices: #; s#^PROP$#prop: airplane_prop_0.ogg#; s#^JET$#jet: engine_takeoff.wav#' | sort -u | paste -sd ';' - | sed 's/;/; /g')"
  [[ -n "$src" ]] || src="synthetic"
  bytes="$(wc -c <"$f" | tr -d ' ')"
  sha="$(shasum -a 256 "$f" | awk '{print $1}')"
  rows+=("| \`$name.ogg\` | $src | $bytes | $(printf '%.3f' "$dur") | $lufs | $tp | \`$sha\` |")
done

if [[ $failures -gt 0 ]]; then
  printf '%s cue(s) failed validation\n' "$failures" >&2
  exit 1
fi
printf 'OK: %s cues validated\n' "${#names[@]}"

if [[ $WRITE -eq 1 ]]; then
  mkdir -p "$(dirname "$MANIFEST")"
  {
    cat <<'EOF'
# Unit SFX manifest (#612)

Generated by `scripts/validate-unit-sfx.sh --write-manifest` from the files `scripts/generate-unit-sfx.sh`
produces. Do not edit by hand. `tests/audio/sfx-coverage.test.ts` fails if a committed file no longer matches
its `sha256` below, so re-run the generator, the validator and this manifest together.

- **Two kinds of cue.** `synthetic` cues are built from ffmpeg lavfi only (seeded `anoisesrc`, `aevalsrc`
  envelopes and tones). The others are *derived* by cutting, pitch-shifting (varispeed), filtering and layering
  the CC0 recordings listed below; the Source column names the exact source files.
- **Source files** (all fetched over HTTPS from the official OpenGameArt page by
  `scripts/fetch-unit-sfx-sources.sh`, SHA-256 pinned, safely extracted, never committed; retrieved 2026-10-02):

  | Set | Page | Author | License | SHA-256 |
  |---|---|---|---|---|
  | `firearms` | https://opengameart.org/content/the-free-firearm-sound-library | Ben Jaszczak, Brian Nelson, Kevin Heras, Matthew Nanney | CC0 1.0 | `cc1ab5a99a0a365105c7c5dd783f4b0b1fe90938114d3ceec53856bfe005f7d6` |
  | `naval` | https://opengameart.org/content/tiny-naval-battle-sounds-set | Iwan Gabovitch (qubodup) | CC0 1.0 | `c2a75c2f93a558dd2a5d8420b6bc0375c2d0e41c1f59a78a925ac6052d6ef05c` |
  | `rts` | https://opengameart.org/content/sci-fi-rts-war-unit-sounds | Iwan Gabovitch (qubodup); sources by Ferdinger, John Sipos, klankbeeld | CC0 1.0 (relicensed from CC-BY-SA 3.0 on 2024-08-28) | `b5dcbdd8e11151c2cb8a242fb9279690b2cb372fcb44d451c6df191a42a1de85` |
  | `voices` | https://opengameart.org/content/male-gruntyelling-sounds | HaelDB | CC0 1.0 (dual-licensed CC0 / OGA-BY 3.0; CC0 chosen) | `e9100a4e3b9dcd146993089970dc6097dcf9935fa4683b196040012bad65d67a` |
  | `prop` | https://opengameart.org/content/airplane-prop-loop | jakobthiesen (Freesound 188423), looped by AntumDeluge | CC-BY 3.0, credit given in `AUDIO-CREDITS.md` | `f835c4f5ab4233058af5bd98fa58da2415ac174a26c29cdeca791bd4e8fa45f8` |
  | `jet` | https://opengameart.org/content/jet-engine-takeoff | dklon | CC-BY 3.0, credit given in `AUDIO-CREDITS.md` | `c7aa06c63a4fc5a638cab2b9f292a34ca03b3f3a1016d01e3b69cfd65f328e87` |

- **License of the cues:** each cue inherits the strictest source it uses: CC0 1.0 (no attribution needed, credited anyway) for all of them except `air-move-prop`, `air-move-jet` and `air-move-drone` (pitched-up propeller), which are CC-BY 3.0 derivatives and require the credits in `AUDIO-CREDITS.md`.
- **Format:** mono, 44.1 kHz, Ogg Vorbis `-q:a 4`, metadata stripped.
- **Normalization:** peak target per cue, then the *encoded* file is re-measured and trimmed until true peak
  is at most -1.2 dBTP; cues of 400 ms or more are capped at -16.5 LUFS integrated. Shorter cues are
  below EBU R128's gating block and are controlled by peak only.
- **Determinism:** two consecutive runs on one machine produce byte-identical files.

| File | Source | Bytes | Duration (s) | Integrated LUFS | True peak (dBTP) | SHA-256 |
|---|---|---:|---:|---:|---:|---|
EOF
    printf '%s\n' "${rows[@]}"
  } >"$MANIFEST"
  printf 'wrote %s\n' "$MANIFEST"
fi
