/** Writes the actual catalog SAM/Radar SVG into the file-safe #710 review page. */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { BUILDING_SPRITE_CATALOG } from '../src/renderer/sprites/sprite-catalog';
import { RadarStationSprite } from '../src/renderer/sprites/buildings';
import { derivePalette } from '../src/renderer/sprites/sprite-system';

const previewPath = resolve(process.cwd(), 'docs/reviews/assets/issue-710/sprite-preview.html');
const startMarker = '<!-- ISSUE_710_BUILDINGS_START -->';
const endMarker = '<!-- ISSUE_710_BUILDINGS_END -->';
const palette = derivePalette('#b53026');
// The SVG namespace declaration is an XML identifier, not a fetch, but the review page
// deliberately rejects every http(s) string so it can prove all evidence is file-safe.
const fileSafeSvg = (markup: string) => markup.replace(/\sxmlns="http:\/\/www\.w3\.org\/2000\/svg"/g, '');
const samSite = fileSafeSvg(BUILDING_SPRITE_CATALOG.sam_site({ palette, svgOnly: true }));
const radarStation = fileSafeSvg(RadarStationSprite({ palette, svgOnly: true }));
const preview = readFileSync(previewPath, 'utf8');
const start = preview.indexOf(startMarker);
const end = preview.indexOf(endMarker);

if (start === -1 || end === -1 || end < start) {
  throw new Error('Issue #710 building preview data markers are missing or malformed.');
}

const payload = JSON.stringify({ sam_site: samSite, radar_station: radarStation }).replace(/</g, '\\u003c');
const generated = [
  startMarker,
  '<script id="issue-710-building-data">',
  '// Auto-generated by scripts/write-issue-710-review-data.ts — do not edit manually.',
  `globalThis.__ISSUE_710_BUILDINGS__ = ${payload};`,
  '</script>',
  endMarker,
].join('\n');

writeFileSync(previewPath, `${preview.slice(0, start)}${generated}${preview.slice(end + endMarker.length)}`);
console.log('✓ Wrote Issue #710 static SAM/Radar review data');
