/**
 * Writes the real catalog payloads for the four #712 defensive assets into the
 * file-safe review page (docs/reviews/assets/issue-712/sprite-preview.html).
 *
 * Run: bash scripts/run-with-mise.sh yarn tsx scripts/write-issue-712-review-data.ts
 * (or via the issue-712 preview test, which regenerates and asserts on the output).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { FORT_MARKER_SVG, CITADEL_MARKER_SVG } from '../src/renderer/improvements/fort-marker';
import { BunkerSprite, CoastalBatterySprite } from '../src/renderer/sprites/buildings';
import { derivePalette } from '../src/renderer/sprites/sprite-system';

const previewPath = resolve(process.cwd(), 'docs/reviews/assets/issue-712/sprite-preview.html');
const startMarker = '<!-- ISSUE_712_DATA_START -->';
const endMarker = '<!-- ISSUE_712_DATA_END -->';

// The SVG namespace declaration is an XML identifier, not a fetch, but the review
// page deliberately rejects every http(s) string so it can prove all evidence is
// file-safe. Strip it from the embedded payloads.
const fileSafe = (markup: string) => markup.replace(/\sxmlns="http:\/\/www\.w3\.org\/2000\/svg"/g, '');

const FACTION_SEEDS: Record<string, string> = {
  crimson: '#c0392b',
  teal: '#1c8a8a',
  gold: '#c79a2e',
};

const perFaction = (fn: typeof BunkerSprite): Record<string, string> => {
  const out: Record<string, string> = {};
  for (const [name, seed] of Object.entries(FACTION_SEEDS)) {
    out[name] = fileSafe(fn({ palette: derivePalette(seed), svgOnly: true }));
  }
  return out;
};

const payload = JSON.stringify({
  fort: fileSafe(FORT_MARKER_SVG),
  citadel: fileSafe(CITADEL_MARKER_SVG),
  bunker: perFaction(BunkerSprite),
  coastal_battery: perFaction(CoastalBatterySprite),
}).replace(/</g, '\\u003c');

const preview = readFileSync(previewPath, 'utf8');
const start = preview.indexOf(startMarker);
const end = preview.indexOf(endMarker);
if (start === -1 || end === -1 || end < start) {
  throw new Error('Issue #712 review data markers are missing or malformed.');
}

const generated = [
  startMarker,
  '<script id="issue-712-data">',
  '// Auto-generated by scripts/write-issue-712-review-data.ts — do not edit manually.',
  `globalThis.__ISSUE_712__ = ${payload};`,
  '</script>',
  endMarker,
].join('\n');

writeFileSync(previewPath, `${preview.slice(0, start)}${generated}${preview.slice(end + endMarker.length)}`);
console.log('✓ Wrote Issue #712 Fort / Citadel / Bunker / Coastal Battery review data');
