import type { WonderSpectacleRecipe } from '@/systems/wonder-spectacle/types';

function recipe(input: Omit<WonderSpectacleRecipe, 'intensity' | 'surfaceSupport'>): WonderSpectacleRecipe {
  return {
    ...input,
    surfaceSupport: ['map', 'codex', 'reveal'],
    intensity: 'spectacle',
  };
}

export const NATURAL_WONDER_SPECTACLE_RECIPES = [
  recipe({
    wonderId: 'great_volcano',
    paletteKey: 'fire',
    affinityTags: ['fire', 'stone', 'nature'],
    mapPrimitives: ['heatGlow', 'smokePlume', 'embers'],
    codexPrimitives: ['heatGlow', 'embers'],
    revealPrimitives: ['heatGlow', 'smokePlume', 'embers', 'stonePulse'],
    reducedMotionFallback: 'static-aura',
    soundMood: 'volcanic-breath',
    timingHints: ['pulse', 'flicker'],
  }),
  recipe({
    wonderId: 'sacred_mountain',
    paletteKey: 'stone',
    affinityTags: ['mountain', 'stone', 'sky'],
    mapPrimitives: ['stonePulse', 'mist'],
    codexPrimitives: ['stonePulse', 'sparkle'],
    revealPrimitives: ['stonePulse', 'mist', 'lightBands'],
    reducedMotionFallback: 'static-landmark',
    soundMood: 'high-wind-chime',
    timingHints: ['slow', 'pulse'],
  }),
  recipe({
    wonderId: 'crystal_caverns',
    paletteKey: 'crystal',
    affinityTags: ['cave', 'stone', 'discovery'],
    mapPrimitives: ['crystalGleam', 'deepWaterAura'],
    codexPrimitives: ['crystalGleam', 'sparkle'],
    revealPrimitives: ['crystalGleam', 'sparkle', 'stonePulse'],
    reducedMotionFallback: 'static-aura',
    soundMood: 'crystal-hum',
    timingHints: ['pulse'],
  }),
  recipe({
    wonderId: 'ancient_forest',
    paletteKey: 'forest',
    affinityTags: ['forest', 'healing', 'nature'],
    mapPrimitives: ['fireflies', 'leafDrift'],
    codexPrimitives: ['fireflies', 'leafDrift'],
    revealPrimitives: ['fireflies', 'leafDrift', 'sparkle'],
    reducedMotionFallback: 'static-landmark',
    soundMood: 'forest-whisper',
    timingHints: ['slow', 'drift'],
  }),
  recipe({
    wonderId: 'coral_reef',
    paletteKey: 'reef',
    affinityTags: ['sea', 'food', 'nature'],
    mapPrimitives: ['waterFlow', 'sparkle'],
    codexPrimitives: ['waterFlow', 'sparkle'],
    revealPrimitives: ['waterFlow', 'sparkle', 'deepWaterAura'],
    reducedMotionFallback: 'static-aura',
    soundMood: 'reef-glimmer',
    timingHints: ['drift', 'pulse'],
  }),
  recipe({
    wonderId: 'grand_canyon',
    paletteKey: 'canyon',
    affinityTags: ['canyon', 'stone', 'earth'],
    mapPrimitives: ['stonePulse', 'mist'],
    codexPrimitives: ['stonePulse', 'sparkle'],
    revealPrimitives: ['stonePulse', 'mist', 'lightBands'],
    reducedMotionFallback: 'static-landmark',
    soundMood: 'canyon-echo',
    timingHints: ['slow'],
  }),
  recipe({
    wonderId: 'aurora_fields',
    paletteKey: 'aurora',
    affinityTags: ['aurora', 'sky', 'science'],
    mapPrimitives: ['lightBands', 'sparkle'],
    codexPrimitives: ['lightBands', 'sparkle'],
    revealPrimitives: ['lightBands', 'sparkle', 'deepWaterAura'],
    reducedMotionFallback: 'static-aura',
    soundMood: 'aurora-shimmer',
    timingHints: ['drift', 'slow'],
  }),
  recipe({
    wonderId: 'frozen_falls',
    paletteKey: 'iceWater',
    affinityTags: ['ice', 'water', 'stone'],
    mapPrimitives: ['waterFlow', 'mist', 'sparkle'],
    codexPrimitives: ['waterFlow', 'mist'],
    revealPrimitives: ['waterFlow', 'mist', 'sparkle', 'stonePulse'],
    reducedMotionFallback: 'static-aura',
    soundMood: 'frozen-fall',
    timingHints: ['drift'],
  }),
  recipe({
    wonderId: 'dragon_bones',
    paletteKey: 'ancientBone',
    affinityTags: ['fossil', 'science', 'ancient'],
    mapPrimitives: ['fossilDust', 'stonePulse'],
    codexPrimitives: ['fossilDust', 'sparkle'],
    revealPrimitives: ['fossilDust', 'stonePulse', 'sparkle'],
    reducedMotionFallback: 'static-landmark',
    soundMood: 'ancient-bones',
    timingHints: ['slow', 'drift'],
  }),
  recipe({
    wonderId: 'singing_sands',
    paletteKey: 'desert',
    affinityTags: ['desert', 'travel', 'culture'],
    mapPrimitives: ['sandRipple', 'sparkle'],
    codexPrimitives: ['sandRipple', 'sparkle'],
    revealPrimitives: ['sandRipple', 'sparkle', 'lightBands'],
    reducedMotionFallback: 'static-aura',
    soundMood: 'singing-sand',
    timingHints: ['drift', 'pulse'],
  }),
  recipe({
    wonderId: 'sunken_ruins',
    paletteKey: 'ruins',
    affinityTags: ['ocean', 'ancient', 'science'],
    mapPrimitives: ['ruinGlimmer', 'deepWaterAura'],
    codexPrimitives: ['ruinGlimmer', 'waterFlow'],
    revealPrimitives: ['ruinGlimmer', 'deepWaterAura', 'waterFlow'],
    reducedMotionFallback: 'static-aura',
    soundMood: 'sunken-ruin',
    timingHints: ['slow', 'drift'],
  }),
  recipe({
    wonderId: 'floating_islands',
    paletteKey: 'skyIsland',
    affinityTags: ['sky', 'stone', 'discovery'],
    mapPrimitives: ['mist', 'leafDrift', 'stonePulse'],
    codexPrimitives: ['mist', 'leafDrift'],
    revealPrimitives: ['mist', 'leafDrift', 'stonePulse', 'lightBands'],
    reducedMotionFallback: 'static-landmark',
    soundMood: 'floating-wind',
    timingHints: ['slow', 'drift'],
  }),
  recipe({
    wonderId: 'bioluminescent_bay',
    paletteKey: 'reef',
    affinityTags: ['sea', 'light', 'science'],
    mapPrimitives: ['deepWaterAura', 'sparkle'],
    codexPrimitives: ['deepWaterAura', 'sparkle'],
    revealPrimitives: ['deepWaterAura', 'sparkle', 'waterFlow'],
    reducedMotionFallback: 'static-aura',
    soundMood: 'glowing-bay',
    timingHints: ['pulse', 'drift'],
  }),
  recipe({
    wonderId: 'bottomless_lake',
    paletteKey: 'deepWater',
    affinityTags: ['water', 'healing', 'science'],
    mapPrimitives: ['deepWaterAura', 'mist'],
    codexPrimitives: ['deepWaterAura', 'sparkle'],
    revealPrimitives: ['deepWaterAura', 'mist', 'sparkle'],
    reducedMotionFallback: 'static-aura',
    soundMood: 'deep-lake',
    timingHints: ['slow', 'pulse'],
  }),
  recipe({
    wonderId: 'eternal_storm',
    paletteKey: 'storm',
    affinityTags: ['storm', 'sky', 'science'],
    mapPrimitives: ['lightning', 'mist'],
    codexPrimitives: ['lightning', 'deepWaterAura'],
    revealPrimitives: ['lightning', 'mist', 'deepWaterAura'],
    reducedMotionFallback: 'static-aura',
    soundMood: 'distant-thunder',
    timingHints: ['flicker', 'pulse'],
  }),
] satisfies WonderSpectacleRecipe[];
