import { TECH_AUDIT_ENTRIES, WARFARE_RECONCILIATION, type TechAuditEntry } from '../systems/tech-audit/tech-audit-data';
import {
  aiValuationPath, deriveJudgement, hasBroadCombatModifier, repeatedNicheSignatures, findRepeatedNiches,
} from './tech-audit-judgement';
import type { TechAuditRow } from './tech-audit-inventory';

export interface ResolvedRow {
  row: TechAuditRow;
  entry: TechAuditEntry;
  authored: boolean;
}

/** Authored entry when one exists, else the derived default. The audit test guarantees flagged techs are authored. */
export function resolveRows(rows: readonly TechAuditRow[]): ResolvedRow[] {
  const repeated = repeatedNicheSignatures(rows);
  return rows.map(row => {
    const authored = TECH_AUDIT_ENTRIES[row.id];
    if (authored) return { row, entry: authored, authored: true };
    return { row, entry: { ...deriveJudgement(row, repeated), child: 0 as const }, authored: false };
  });
}

const BANDS: Array<{ label: string; from: number; to: number; child: 2 | 3 | 4 }> = [
  { label: 'Eras 1–4', from: 1, to: 4, child: 2 },
  { label: 'Eras 5–8', from: 5, to: 8, child: 3 },
  { label: 'Eras 9–11', from: 9, to: 11, child: 4 },
];

function escapeCell(text: string): string {
  return text.replace(/\|/g, '\\|');
}

function effectSummary(row: TechAuditRow): string {
  const parts = [
    ...row.yieldEffects.map(effect => effect.label),
    ...row.costDiscounts.map(discount => `discount ${discount}`),
    ...row.unitModifiers.map(modifier => modifier.summary),
  ];
  return parts.length ? parts.join('; ') : '-';
}

export function renderTechAuditReport(rows: readonly TechAuditRow[]): string {
  const resolved = resolveRows(rows);
  const out: string[] = [];
  const counts = (pred: (r: ResolvedRow) => boolean): number => resolved.filter(pred).length;

  out.push('# Tech strategic-choice audit (#420, child 1)', '');
  out.push('Generated by `tests/helpers/tech-audit-report.ts` from `src/` and `tests/systems/tech-audit/tech-audit-data.ts`; pinned by');
  out.push('`tests/systems/tech-strategic-audit.test.ts`. Regenerate with `UPDATE_TECH_AUDIT=1 ./scripts/dev.sh test tests/systems/tech-strategic-audit.test.ts`.');
  out.push('Scope: Eras 1–11 are audited for change; Era 12 is reference (listed, left unscheduled); Era 13+ is out of scope.', '');

  out.push('## Classification totals', '');
  out.push('| Class | Count |', '|---|---:|');
  for (const cls of ['KEEP', 'TUNE', 'REPLACE', 'WIRE', 'FOLLOW-UP', 'OBSOLETE'] as const) {
    out.push(`| ${cls} | ${counts(r => r.entry.cls === cls)} |`);
  }
  out.push(`| **Total (Eras 1–12)** | ${resolved.length} |`, '');

  out.push('## Low-signal patterns by era', '');
  out.push('| Era | Techs | cityFlat | empireFlat | empirePercent | Broad combat | Conditional/scaling yield | Unit modifier (scoped) | No table effect |');
  out.push('|---:|---:|---:|---:|---:|---:|---:|---:|---:|');
  const eras = [...new Set(rows.map(r => r.era))].sort((a, b) => a - b);
  for (const era of eras) {
    const inEra = rows.filter(r => r.era === era);
    const kind = (k: string): number => inEra.filter(r => r.yieldEffects.some(e => e.kind === k)).length;
    const flatKinds = new Set(['cityFlat', 'empireFlat', 'empirePercent']);
    const conditional = inEra.filter(r => r.yieldEffects.some(e => !flatKinds.has(e.kind))).length;
    const scoped = inEra.filter(r => r.unitModifiers.length > 0 && !hasBroadCombatModifier(r)).length;
    const none = inEra.filter(r => r.yieldEffects.length + r.unitModifiers.length + r.costDiscounts.length === 0).length;
    out.push(`| ${era} | ${inEra.length} | ${kind('cityFlat')} | ${kind('empireFlat')} | ${kind('empirePercent')} | ${inEra.filter(hasBroadCombatModifier).length} | ${conditional} | ${scoped} | ${none} |`);
  }
  out.push('');
  out.push('"No table effect" techs act through unlocked content or bespoke code (see Code owners in the inventory); Eras 1–4 have no yield-table rows at all.', '');

  out.push('## Repeated niches (three or more techs, same shape)', '');
  for (const group of findRepeatedNiches(rows)) out.push(`- \`${group.signature}\` ×${group.techIds.length}: ${group.techIds.join(', ')}`);
  out.push('');

  out.push('## AI valuation path', '');
  out.push('`evaluateAITechCapabilities` (src/ai/ai-tech-evaluation.ts) values unlocked units, unlocked buildings, revealed resources, era and `tech.pacing`, plus (since #1304) a bounded value for the tech\'s own yield, cost-discount and combat-modifier rows (`getTechEconomicEffectValue`, capped at 3; `getTechCombatEffectValue`, capped at 0.5). Effects owned by bespoke code (espionage, crisis, unrest) are valued only through the unlocks that carry them.', '');
  out.push('| Path | Meaning | Techs |', '|---|---|---:|');
  const meaning: Record<string, string> = {
    'unlock+effect-valued': 'unlocks valued; own table effect valued by the bounded term',
    'effect-valued': 'table effect only, valued by the bounded term',
    'unlock-valued': 'valued through unlocks',
    'era-only': 'era progress only',
  };
  for (const path of Object.keys(meaning)) out.push(`| ${path} | ${meaning[path]} | ${rows.filter(r => aiValuationPath(r) === path).length} |`);
  out.push('', 'The effect term is state-independent (it prices scaling rows at a small assumed count) so it never reads opponent state; it makes a rewritten effect visible to research planning without making any one tech dominate.', '');

  for (const band of BANDS) {
    out.push(`## Child ${band.child} target list — ${band.label}`, '');
    const targets = resolved.filter(r => r.row.era >= band.from && r.row.era <= band.to && r.entry.child === band.child && r.entry.cls !== 'KEEP');
    const keepsWithText = resolved.filter(r => r.row.era >= band.from && r.row.era <= band.to && r.entry.child === band.child && r.entry.cls === 'KEEP');
    out.push(`${targets.length} techs to change; ${keepsWithText.length} scheduled for verification/text only.`, '');
    out.push('| Tech | Era | Class | Today | Candidate (existing mechanics) |', '|---|---:|---|---|---|');
    for (const { row, entry } of targets) {
      out.push(`| \`${row.id}\` | ${row.era} | ${entry.cls}${entry.textFix ? ' + text' : ''} | ${escapeCell(effectSummary(row))} | ${escapeCell(entry.candidate ?? '')} |`);
    }
    out.push('');
    if (keepsWithText.length) {
      out.push('Verify only: ' + keepsWithText.map(r => `\`${r.row.id}\``).join(', '), '');
    }
  }

  out.push('## Warfare brainstorm reconciliation (#420 Part 2)', '');
  out.push('| Era | Kind | Idea | Status | Evidence |', '|---:|---|---|---|---|');
  for (const w of WARFARE_RECONCILIATION) {
    out.push(`| ${w.era} | ${w.kind} | ${escapeCell(w.idea)} | ${w.status} | ${escapeCell(w.evidence)} |`);
  }
  out.push('');

  out.push('## Full inventory', '');
  out.push('Class/rating: rating 0 flavor, 1 unconditional number, 2 conditional but weak or repeated, 3 capability/scaling/system verb.', '');
  out.push('| Tech | Era | Track | Class | Rating | AI path | Effects | Code owners |', '|---|---:|---|---|---:|---|---|---|');
  for (const { row, entry } of resolved) {
    out.push(`| \`${row.id}\` | ${row.era} | ${row.track} | ${entry.cls} | ${entry.rating} | ${aiValuationPath(row)} | ${escapeCell(effectSummary(row))} | ${row.codeOwners.join(', ') || '-'} |`);
  }
  out.push('');
  return out.join('\n');
}
