import type { WonderCodexContent } from '@/systems/wonder-codex/types';

export const LEGENDARY_WONDER_CODEX_CONTENT = [
  legendary(
    'oracle-of-delphi',
    'Oracle of Delphi',
    'A civic voice built around mystery, counsel, and interpretation.',
    'The Oracle of Delphi turns uncertainty into institution. Pilgrims arrive with questions, rulers arrive with fear, and the host city learns to make listening itself a form of power.',
    'The real Delphi was a major sanctuary in ancient Greece, famous for the oracle of Apollo and for drawing visitors from many communities.',
    'reverence',
    ['knowledge', 'faith', 'science', 'ancient', 'culture'],
    ['unesco-delphi'],
    'image-delphi',
    ['knowledge', 'faith', 'science'],
    'Questions Made Public',
    'The oracle gives private fear a public setting: counsel, ambiguity, and civic prestige.',
    'Knowledge as Legacy',
    'Its reward is framed as research because the wonder represents organized attention to signs and records.',
  ),
  legendary(
    'grand-canal',
    'Grand Canal',
    'A water road that turns distance into connection.',
    'The Grand Canal is a promise that cities do not have to stay separate. Water, labor, locks, boats, and planning become one long civic machine.',
    'The real Grand Canal of China connected major river systems and supported transport, trade, and administration across a huge region.',
    'ingenuity',
    ['water', 'engineering', 'trade', 'food', 'gold'],
    ['unesco-grand-canal'],
    'image-canal',
    ['water', 'engineering', 'trade'],
    'Engineered Water',
    'A canal is not only dug earth; it is a city system stretched across the map.',
    'Food in Motion',
    'Its rewards fit a wonder that moves grain, people, tools, and news.',
  ),
  legendary(
    'sun-spire',
    'Sun Spire',
    'A tower that teaches the city to organize itself around light.',
    'The Sun Spire rises like a fixed sunrise. Its purpose is part monument, part calendar, and part reminder that energy can be gathered by paying attention.',
    'Solar technologies turn sunlight into useful energy. Even before modern panels, many buildings used sunlight for heat, timing, and orientation.',
    'awe',
    ['light', 'faith', 'production', 'gold', 'engineering'],
    ['energy-solar'],
    'image-volcano',
    ['light', 'faith', 'engineering'],
    'Measured Day',
    'The tower makes the passage of light feel like civic knowledge.',
    'Radiant Labor',
    'Its production reward fits a place where design turns nature into useful work.',
  ),
  legendary(
    'world-archive',
    'World Archive',
    'A memory house for maps, laws, letters, and arguments.',
    'The World Archive is where a civilization admits that forgetting is dangerous. Shelves, indexes, and careful copying become tools of survival.',
    'Large libraries and archives preserve books, records, maps, and other materials so people can study, verify, and remember information over time.',
    'memory',
    ['archive', 'knowledge', 'science', 'culture', 'ancient'],
    ['loc-about'],
    'image-archive',
    ['archive', 'knowledge', 'science'],
    'Stored Voices',
    'The archive makes old decisions available to future citizens.',
    'Proof Against Rumor',
    'Its empire-wide science reward fits a society that can check what it knows.',
  ),
  legendary(
    'moonwell-gardens',
    'Moonwell Gardens',
    'A cultivated sanctuary where beauty is also public work.',
    'The Moonwell Gardens make a city feel cared for. Paths, water, night-blooming plants, and careful planting turn food and learning into ceremony.',
    'Botanic gardens can conserve plants, teach visitors, and support research. They show that gardens can be scientific and cultural spaces.',
    'reverence',
    ['forest', 'food', 'science', 'healing', 'culture'],
    ['bgci-gardens'],
    'image-garden',
    ['forest', 'food', 'science'],
    'Designed Growth',
    'The garden feels natural, but its wonder comes from patient planning.',
    'Living Collection',
    'Its food and science reward fits a place where cultivation becomes knowledge.',
  ),
  legendary(
    'ironroot-foundry',
    'Ironroot Foundry',
    'A hot industrial heart sunk into old earth.',
    'The Ironroot Foundry gives the city a sound: hammer, bellows, wheel, and quenching steam. It makes raw ore feel like future tools.',
    'Historic ironworks used furnaces, waterpower, charcoal, and skilled labor to turn ore into useful metal for tools, buildings, and transport.',
    'ingenuity',
    ['industry', 'production', 'science', 'stone', 'engineering'],
    ['nps-saugus-iron'],
    'image-foundry',
    ['industry', 'production', 'engineering'],
    'Heat and Skill',
    'The foundry is a workshop scaled up until it changes the city around it.',
    'Tools Become Policy',
    'Its reward fits a wonder where better materials unlock bigger plans.',
  ),
  legendary(
    'tidecaller-bastion',
    'Tidecaller Bastion',
    'A coastal fortress that listens to weather, trade, and threat.',
    'The Tidecaller Bastion stands where waves, roads, and warnings meet. It protects the harbor, but it also teaches the city to read the sea.',
    'Coastal communities have long used forts, harbors, signals, and charts to manage travel, defense, and trade along the water.',
    'danger',
    ['coast', 'defense', 'trade', 'sea', 'production'],
    ['noaa-maritime-heritage'],
    'image-ruins',
    ['coast', 'defense', 'trade'],
    'Harbor Shield',
    'The bastion turns the edge of the map into a guarded doorway.',
    'Tide Knowledge',
    'Its rewards fit a city that treats coastlines as infrastructure.',
  ),
  legendary(
    'starvault-observatory',
    'Starvault Observatory',
    'A night machine for questions too large for daylight.',
    'The Starvault Observatory makes patience heroic. Its builders polish lenses, mark angles, and teach the city that looking carefully is a kind of courage.',
    'Observatories help scientists study light from space. They can reveal planets, stars, galaxies, and events that are invisible to ordinary sight.',
    'discovery',
    ['sky', 'science', 'knowledge', 'light', 'discovery'],
    ['nasa-observatories'],
    'image-observatory',
    ['sky', 'science', 'discovery'],
    'Careful Looking',
    'The observatory turns night into a working surface.',
    'Far Evidence',
    'Its science reward fits a wonder that gathers proof from beyond the city.',
  ),
  legendary(
    'whispering-exchange',
    'Whispering Exchange',
    'A market of signals, bargains, credit, and rumor.',
    'The Whispering Exchange makes trade feel almost invisible. Prices move, messages travel, and the city learns that information can be as valuable as cargo.',
    'Trade networks rely on trust, records, transport, and communication. Markets work best when people can compare value and keep promises across distance.',
    'prosperity',
    ['trade', 'gold', 'knowledge', 'culture', 'travel'],
    ['internet-society-history'],
    'image-archive',
    ['trade', 'gold', 'knowledge'],
    'Quiet Deals',
    'The exchange rewards attention to small signals before they become public news.',
    'Value in Motion',
    'Its gold and science reward fits commerce guided by information.',
  ),
  legendary(
    'hall-of-champions',
    'Hall of Champions',
    'A public memory of contests, victories, and names worth repeating.',
    'The Hall of Champions is not only for winners. It is where a society decides which struggles should be remembered and which examples should guide the next generation.',
    'The ancient Olympic Games were athletic and religious festivals where competitors represented communities and victories became part of public memory.',
    'memory',
    ['military', 'culture', 'ancient', 'production', 'gold'],
    ['olympics-ancient'],
    'image-fossil',
    ['military', 'culture', 'ancient'],
    'Names in Stone',
    'The hall turns individual action into civic story.',
    'Contest and Training',
    'Its reward fits a place that links discipline, fame, and organized strength.',
  ),
  legendary(
    'gate-of-the-world',
    'Gate of the World',
    'A harbor threshold for journeys past the familiar edge.',
    'The Gate of the World makes departure feel official. Ships leave through it carrying maps, fears, goods, and the possibility of return.',
    'Maritime routes connected communities through exploration, migration, trade, and shared technology. Ports often became places where cultures met.',
    'discovery',
    ['coast', 'travel', 'trade', 'science', 'discovery'],
    ['noaa-maritime-heritage'],
    'image-ruins',
    ['coast', 'travel', 'discovery'],
    'Beyond the Breakwater',
    'The gate makes long-range travel feel like a civic project.',
    'World Contact',
    'Its rewards fit a wonder that expands the map through exchange.',
  ),
  legendary(
    'leviathan-drydock',
    'Leviathan Drydock',
    'A shipyard built for vessels larger than local imagination.',
    'The Leviathan Drydock turns the shore into a workshop. Timber, stone, rope, metal, and planning gather around the dream of commanding open water.',
    'Drydocks let workers build and repair ships out of the water. Large shipyards can become centers of engineering, labor, and maritime power.',
    'ingenuity',
    ['coast', 'engineering', 'production', 'trade', 'sea'],
    ['noaa-maritime-heritage'],
    'image-ruins',
    ['coast', 'engineering', 'production'],
    'Work Below the Waterline',
    'The drydock reveals the hidden labor that makes seafaring possible.',
    'Harbor Industry',
    'Its city reward fits a place where trade and construction share the same waterfront.',
  ),
  legendary(
    'storm-signal-spire',
    'Storm-Signal Spire',
    'A tower for warnings before the sky becomes dangerous.',
    'The Storm-Signal Spire makes attention public. It gathers reports, watches the horizon, and turns weather into signals a city can act on.',
    'Weather-warning networks help communities prepare for dangerous storms. Radios, towers, satellites, and local reports all support faster warnings.',
    'danger',
    ['storm', 'sky', 'science', 'gold', 'modern'],
    ['noaa-weather-radio'],
    'image-storm',
    ['storm', 'sky', 'science'],
    'Warning as Infrastructure',
    'The spire makes safety feel built, not accidental.',
    'Signals Across Distance',
    'Its reward fits a modern society that converts observation into action.',
  ),
  legendary(
    'manhattan-project',
    'Manhattan Project',
    'A secret research effort with world-changing consequences.',
    'The Manhattan Project is presented carefully: a wonder of organization and science, but also a warning about responsibility. Power this large changes history and demands reflection.',
    'The real Manhattan Project was a World War II program that developed the first nuclear weapons. It involved many sites, scientists, workers, and serious ethical consequences.',
    'danger',
    ['modern', 'science', 'industry', 'military', 'knowledge'],
    ['nps-manhattan-project'],
    'image-manhattan',
    ['modern', 'science', 'industry'],
    'Secret Cities',
    'The project shows how research, industry, and government can combine at enormous scale.',
    'Power and Responsibility',
    'The codex should make clear that scientific achievement can carry moral weight.',
  ),
  legendary(
    'internet',
    'Internet',
    'A network of networks that changes how knowledge travels.',
    'The Internet wonder makes distance feel different. Messages, research, trade, and culture move through shared protocols instead of roads alone.',
    'The Internet grew from earlier research networks into a global system of connected networks. It lets many kinds of devices exchange information using shared rules.',
    'discovery',
    ['modern', 'knowledge', 'trade', 'science', 'archive'],
    ['internet-society-history'],
    'image-internet',
    ['modern', 'knowledge', 'trade'],
    'Many Networks',
    'The Internet is powerful because it links systems rather than replacing every local system.',
    'Fast Memory',
    'Its reward fits a civilization where information moves quickly and widely.',
  ),
] satisfies WonderCodexContent[];

function legendary(
  id: string,
  title: string,
  subtitle: string,
  authoredLead: string,
  learningText: string,
  visualTone: WonderCodexContent['visualTone'],
  tags: WonderCodexContent['tags'],
  factSourceIds: string[],
  imageSourceId: string,
  relatedSeedTags: WonderCodexContent['relatedSeedTags'],
  firstHeading: string,
  firstBody: string,
  secondHeading: string,
  secondBody: string,
): WonderCodexContent {
  return {
    id,
    kind: 'legendary',
    title,
    subtitle,
    authoredLead,
    learningText,
    visualTone,
    tags,
    relatedSeedTags,
    factSourceIds,
    imageSourceId,
    statusHooks: ['legendary-status', 'legendary-reward', 'legendary-host-city', 'legendary-progress'],
    sections: [
      { kind: 'ritual', heading: firstHeading, body: firstBody },
      { kind: 'reward', heading: secondHeading, body: secondBody },
    ],
  };
}
