import type { WonderCodexContent } from '@/systems/wonder-codex/types';

export const LEGENDARY_WONDER_CODEX_CONTENT = [
  legendary(
    'oracle-of-delphi',
    'Oracle of Delphi',
    'A civic voice built around mystery, counsel, and interpretation.',
    'The Oracle of Delphi turns uncertainty into institution. Pilgrims arrive with questions, rulers arrive with fear, and the host city learns to make listening itself a form of power.',
    'The real Delphi was a major sanctuary in ancient Greece, famous for the oracle of Apollo and for drawing visitors from many communities.',
    'reverence',
    ['knowledge', 'faith', 'science', 'ancient', 'culture'],
    ['unesco-delphi'],
    'image-delphi',
    ['knowledge', 'faith', 'science'],
    'Questions Made Public',
    'The oracle gives private fear a public setting: counsel, ambiguity, and civic prestige.',
    'Knowledge as Legacy',
    'Its reward is framed as research because the wonder represents organized attention to signs and records.',
  ),
  legendary(
    'grand-canal',
    'Grand Canal',
    'A water road that turns distance into connection.',
    'The Grand Canal is a promise that cities do not have to stay separate. Water, labor, locks, boats, and planning become one long civic machine.',
    'The real Grand Canal of China connected major river systems and supported transport, trade, and administration across a huge region.',
    'ingenuity',
    ['water', 'engineering', 'trade', 'food', 'gold'],
    ['unesco-grand-canal'],
    'image-canal',
    ['water', 'engineering', 'trade'],
    'Engineered Water',
    'A canal is not only dug earth; it is a city system stretched across the map.',
    'Food in Motion',
    'Its rewards fit a wonder that moves grain, people, tools, and news.',
  ),
  legendary(
    'sun-spire',
    'Sun Spire',
    'A tower that teaches the city to organize itself around light.',
    'The Sun Spire rises like a fixed sunrise. Its purpose is part monument, part calendar, and part reminder that energy can be gathered by paying attention.',
    'Solar technologies turn sunlight into useful energy. Even before modern panels, many buildings used sunlight for heat, timing, and orientation.',
    'awe',
    ['light', 'faith', 'production', 'gold', 'engineering'],
    ['energy-solar'],
    'image-sun-tower',
    ['light', 'faith', 'engineering'],
    'Measured Day',
    'The tower makes the passage of light feel like civic knowledge.',
    'Radiant Labor',
    'Its production reward fits a place where design turns nature into useful work.',
  ),
  legendary(
    'world-archive',
    'World Archive',
    'A memory house for maps, laws, letters, and arguments.',
    'The World Archive is where a civilization admits that forgetting is dangerous. Shelves, indexes, and careful copying become tools of survival.',
    'Large libraries and archives preserve books, records, maps, and other materials so people can study, verify, and remember information over time.',
    'memory',
    ['archive', 'knowledge', 'science', 'culture', 'ancient'],
    ['loc-about'],
    'image-archive',
    ['archive', 'knowledge', 'science'],
    'Stored Voices',
    'The archive makes old decisions available to future citizens.',
    'Proof Against Rumor',
    'Its empire-wide science reward fits a society that can check what it knows.',
  ),
  legendary(
    'moonwell-gardens',
    'Moonwell Gardens',
    'A cultivated sanctuary where beauty is also public work.',
    'The Moonwell Gardens make a city feel cared for. Paths, water, night-blooming plants, and careful planting turn food and learning into ceremony.',
    'Botanic gardens can conserve plants, teach visitors, and support research. They show that gardens can be scientific and cultural spaces.',
    'reverence',
    ['forest', 'food', 'science', 'healing', 'culture'],
    ['bgci-gardens'],
    'image-garden',
    ['forest', 'food', 'science'],
    'Designed Growth',
    'The garden feels natural, but its wonder comes from patient planning.',
    'Living Collection',
    'Its food and science reward fits a place where cultivation becomes knowledge.',
  ),
  legendary(
    'ironroot-foundry',
    'Ironroot Foundry',
    'A hot industrial heart sunk into old earth.',
    'The Ironroot Foundry gives the city a sound: hammer, bellows, wheel, and quenching steam. It makes raw ore feel like future tools.',
    'Historic ironworks used furnaces, waterpower, charcoal, and skilled labor to turn ore into useful metal for tools, buildings, and transport.',
    'ingenuity',
    ['industry', 'production', 'science', 'stone', 'engineering'],
    ['nps-saugus-iron'],
    'image-foundry',
    ['industry', 'production', 'engineering'],
    'Heat and Skill',
    'The foundry is a workshop scaled up until it changes the city around it.',
    'Tools Become Policy',
    'Its reward fits a wonder where better materials unlock bigger plans.',
  ),
  legendary(
    'tidecaller-bastion',
    'Tidecaller Bastion',
    'A coastal fortress that listens to weather, trade, and threat.',
    'The Tidecaller Bastion stands where waves, roads, and warnings meet. It protects the harbor, but it also teaches the city to read the sea.',
    'Coastal communities have long used forts, harbors, signals, and charts to manage travel, defense, and trade along the water.',
    'danger',
    ['coast', 'defense', 'trade', 'sea', 'production'],
    ['noaa-maritime-heritage'],
    'image-ruins',
    ['coast', 'defense', 'trade'],
    'Harbor Shield',
    'The bastion turns the edge of the map into a guarded doorway.',
    'Tide Knowledge',
    'Its rewards fit a city that treats coastlines as infrastructure.',
  ),
  legendary(
    'starvault-observatory',
    'Starvault Observatory',
    'A night machine for questions too large for daylight.',
    'The Starvault Observatory makes patience heroic. Its builders polish lenses, mark angles, and teach the city that looking carefully is a kind of courage.',
    'Observatories help scientists study light from space. They can reveal planets, stars, galaxies, and events that are invisible to ordinary sight.',
    'discovery',
    ['sky', 'science', 'knowledge', 'light', 'discovery'],
    ['nasa-observatories'],
    'image-observatory',
    ['sky', 'science', 'discovery'],
    'Careful Looking',
    'The observatory turns night into a working surface.',
    'Far Evidence',
    'Its science reward fits a wonder that gathers proof from beyond the city.',
  ),
  legendary(
    'whispering-exchange',
    'Whispering Exchange',
    'A market of signals, bargains, credit, and rumor.',
    'The Whispering Exchange makes trade feel almost invisible. Prices move, messages travel, and the city learns that information can be as valuable as cargo.',
    'Trade networks rely on trust, records, transport, and communication. Markets work best when people can compare value and keep promises across distance.',
    'prosperity',
    ['trade', 'gold', 'knowledge', 'culture', 'travel'],
    ['khan-trade-networks'],
    'image-exchange',
    ['trade', 'gold', 'knowledge'],
    'Quiet Deals',
    'The exchange rewards attention to small signals before they become public news.',
    'Value in Motion',
    'Its gold and science reward fits commerce guided by information.',
  ),
  legendary(
    'hall-of-champions',
    'Hall of Champions',
    'A public memory of contests, victories, and names worth repeating.',
    'The Hall of Champions is not only for winners. It is where a society decides which struggles should be remembered and which examples should guide the next generation.',
    'The ancient Olympic Games were athletic and religious festivals where competitors represented communities and victories became part of public memory.',
    'memory',
    ['military', 'culture', 'ancient', 'production', 'gold'],
    ['olympics-ancient'],
    'image-olympia-stadium',
    ['military', 'culture', 'ancient'],
    'Names in Stone',
    'The hall turns individual action into civic story.',
    'Contest and Training',
    'Its reward fits a place that links discipline, fame, and organized strength.',
  ),
  legendary(
    'gate-of-the-world',
    'Gate of the World',
    'A harbor threshold for journeys past the familiar edge.',
    'The Gate of the World makes departure feel official. Ships leave through it carrying maps, fears, goods, and the possibility of return.',
    'Maritime routes connected communities through exploration, migration, trade, and shared technology. Ports often became places where cultures met.',
    'discovery',
    ['coast', 'travel', 'trade', 'science', 'discovery'],
    ['noaa-maritime-heritage'],
    'image-ruins',
    ['coast', 'travel', 'discovery'],
    'Beyond the Breakwater',
    'The gate makes long-range travel feel like a civic project.',
    'World Contact',
    'Its rewards fit a wonder that expands the map through exchange.',
  ),
  legendary(
    'leviathan-drydock',
    'Leviathan Drydock',
    'A shipyard built for vessels larger than local imagination.',
    'The Leviathan Drydock turns the shore into a workshop. Timber, stone, rope, metal, and planning gather around the dream of commanding open water.',
    'Drydocks let workers build and repair ships out of the water. Large shipyards can become centers of engineering, labor, and maritime power.',
    'ingenuity',
    ['coast', 'engineering', 'production', 'trade', 'sea'],
    ['noaa-maritime-heritage'],
    'image-drydock',
    ['coast', 'engineering', 'production'],
    'Work Below the Waterline',
    'The drydock reveals the hidden labor that makes seafaring possible.',
    'Harbor Industry',
    'Its city reward fits a place where trade and construction share the same waterfront.',
  ),
  legendary(
    'storm-signal-spire',
    'Storm-Signal Spire',
    'A tower for warnings before the sky becomes dangerous.',
    'The Storm-Signal Spire makes attention public. It gathers reports, watches the horizon, and turns weather into signals a city can act on.',
    'Weather-warning networks help communities prepare for dangerous storms. Radios, towers, satellites, and local reports all support faster warnings.',
    'danger',
    ['storm', 'sky', 'science', 'gold', 'modern'],
    ['noaa-weather-radio'],
    'image-storm',
    ['storm', 'sky', 'science'],
    'Warning as Infrastructure',
    'The spire makes safety feel built, not accidental.',
    'Signals Across Distance',
    'Its reward fits a modern society that converts observation into action.',
  ),
  legendary(
    'manhattan-project',
    'Manhattan Project',
    'A secret research effort with world-changing consequences.',
    'The Manhattan Project is presented carefully: a wonder of organization and science, but also a warning about responsibility. Power this large changes history and demands reflection.',
    'The real Manhattan Project was a World War II program that developed the first nuclear weapons. It involved many sites, scientists, workers, and serious ethical consequences.',
    'danger',
    ['modern', 'science', 'industry', 'military', 'knowledge'],
    ['nps-manhattan-project'],
    'image-manhattan',
    ['modern', 'science', 'industry'],
    'Secret Cities',
    'The project shows how research, industry, and government can combine at enormous scale.',
    'Power and Responsibility',
    'The codex should make clear that scientific achievement can carry moral weight.',
  ),
  legendary(
    'internet',
    'Internet',
    'A network of networks that changes how knowledge travels.',
    'The Internet wonder makes distance feel different. Messages, research, trade, and culture move through shared protocols instead of roads alone.',
    'The Internet grew from earlier research networks into a global system of connected networks. It lets many kinds of devices exchange information using shared rules.',
    'discovery',
    ['modern', 'knowledge', 'trade', 'science', 'archive'],
    ['internet-society-history'],
    'image-internet',
    ['modern', 'knowledge', 'trade'],
    'Many Networks',
    'The Internet is powerful because it links systems rather than replacing every local system.',
    'Fast Memory',
    'Its reward fits a civilization where information moves quickly and widely.',
  ),
  // Era 5 wonders (Renaissance)
  legendary(
    'sistine-vault',
    'Sistine Vault',
    'A painted ceiling that turns a room into a world.',
    'The Sistine Vault is where art and belief reinforce each other. Its builders brought painters, sculptors, and theologians together under a single program of meaning.',
    'Many famous painted ceilings and vaulted spaces came from an era when patrons believed that beauty in sacred spaces was itself a form of worship.',
    'reverence',
    ['culture', 'knowledge', 'faith', 'gold', 'stone'],
    ['loc-about'],
    'image-archive',
    ['culture', 'knowledge', 'faith'],
    'Patronage and Vision',
    'The Vault shows how organized belief can produce lasting art.',
    'Beauty as Authority',
    'Its yield fits a civilization that invested in shared cultural identity.',
  ),
  legendary(
    'codex-eternal',
    'Codex Eternal',
    'A library of method, not just memory.',
    'The Codex Eternal preserves the rules of inquiry alongside the results. Every discovery gets a method, every method gets a record, and every record waits for the next reader.',
    'The printing press and the scientific method together changed how knowledge traveled. Books made repeatable experiment possible at a distance.',
    'ingenuity',
    ['science', 'knowledge', 'archive', 'production', 'trade'],
    ['loc-about'],
    'image-archive',
    ['science', 'knowledge', 'archive'],
    'The Method Preserved',
    'A codex that outlasts its authors is a gift to every civilization that comes after.',
    'Science as Accumulation',
    'Its reward fits a civilization where discovery builds on discovery.',
  ),
  legendary(
    'navigators-compass',
    "Navigator's Compass",
    'A tool that made the unknown navigable.',
    "The Navigator's Compass wonder shows that exploration is a skill, not a miracle. It trained sailors, recorded routes, and turned guessing into method.",
    'The compass helped sailors move through open water by giving them a direction that did not depend on visible stars or landmarks.',
    'discovery',
    ['coast', 'discovery', 'trade', 'sea', 'gold'],
    ['noaa-maritime-heritage'],
    'image-drydock',
    ['coast', 'discovery', 'trade'],
    'Direction Without Landmarks',
    'The compass removed the fear of open water and made long routes repeatable.',
    'Mapping the Routes',
    'Its reward fits a civilization that built wealth by finding what others had not yet seen.',
  ),
  legendary(
    'palace-of-the-sun',
    'Palace of the Sun',
    'Where power and beauty became one.',
    'The Palace of the Sun is where the ruler becomes the state. It fills entire cities with artisans, courtiers, and administrators organized around a single center of gravity.',
    'The grandest royal palaces in history were economic engines as well as symbols. They concentrated craftsmen, kept courts employed, and showed rivals what wealth could build.',
    'reverence',
    ['gold', 'culture', 'production', 'stone', 'knowledge'],
    ['loc-about'],
    'image-sun-tower',
    ['gold', 'culture', 'production'],
    'Patronage at Scale',
    'A palace vast enough to employ a city makes art a public project.',
    'Wealth Made Visible',
    'Its yields fit a civilization that converted surplus into lasting prestige.',
  ),
  legendary(
    'iron-arsenal',
    'Iron Arsenal',
    'The forge that outfitted an empire.',
    'The Iron Arsenal shows that military power rests on logistics. It standardizes equipment, trains smiths, and keeps weapons flowing to every front — not just the ones the ruler can watch.',
    'Arsenal cities in early modern history were industrial secrets as well as fortifications. The Venetian Arsenal could build a galley in a day; the Venetian state protected its methods accordingly.',
    'awe',
    ['production', 'military', 'stone', 'industry', 'knowledge'],
    ['loc-about'],
    'image-foundry',
    ['production', 'military', 'industry'],
    'Standardized Strength',
    'Interchangeable parts and trained smiths made armies predictable in a way individual craftsmanship could not match.',
    'Logistics as Power',
    'Its reward fits a civilization that treated military capacity as a public work.',
  ),
  legendary(
    'merchant-admiralty',
    'Merchant Admiralty',
    'The institution that turned sailors into a system.',
    'The Merchant Admiralty sits at the place where private shipping and state power overlap. It licenses routes, arbitrates disputes, and collects fees — while the merchants profit from the protection.',
    'Early admiralties gave shipping lanes a legal existence. A route that could be defended in court was more valuable than one defended only by a single captain\'s reputation.',
    'prosperity',
    ['gold', 'coast', 'trade', 'sea', 'discovery'],
    ['noaa-maritime-heritage'],
    'image-drydock',
    ['gold', 'coast', 'trade'],
    'Law of the Sea',
    'An admiralty court gave merchants something no fleet alone could provide: a predictable outcome.',
    'Maritime Income as Empire',
    'Its yield fits a civilization that treated the sea as a tax base.',
  ),
  legendary(
    'crystal-palace',
    'Crystal Palace',
    'Iron and glass in service of wonder.',
    'The Crystal Palace is proof that industry can produce beauty at scale. A vast hall of prefabricated iron ribs and plate glass, it became the symbol of a civilization that could build anything — and chose to exhibit everything.',
    'The original Crystal Palace in Hyde Park, 1851, was designed by Joseph Paxton and housed the Great Exhibition of industry and science. It could be erected in months and housed over six million visitors.',
    'ingenuity',
    ['production', 'science', 'industry', 'light', 'knowledge'],
    ['loc-about'],
    'image-foundry',
    ['production', 'science', 'industry'],
    'Prefabrication at Scale',
    'The secret of the Crystal Palace was not the materials but the method: standardized components assembled by the thousands.',
    'Industry as Exhibition',
    'Its reward fits a civilization that treats scientific production not as a means to an end but as a spectacle worth celebrating.',
  ),
  legendary(
    'suez-canal',
    'Suez Canal',
    'The trench that shortened the world.',
    'The Suez Canal is not just a channel through the sand — it is a decision about who controls the shortest path between two seas. Whoever builds it claims a toll on every ship that values speed over distance.',
    'Completed in 1869, the Suez Canal reduced the sea journey between Britain and India by thousands of miles. It transformed global trade routes overnight and became one of the most strategically contested waterways in history.',
    'discovery',
    ['gold', 'coast', 'trade', 'engineering', 'military'],
    ['noaa-maritime-heritage'],
    'image-drydock',
    ['gold', 'coast', 'trade'],
    'Shortcut as Empire',
    'A canal is not just geography — it is a claim on the economic value of time.',
    'Trade as Tax',
    'Its yield fits a civilization that understood that the sea itself could be made to pay.',
  ),
  legendary(
    'continental-congress',
    'Continental Congress',
    'Where a nation decided what it was.',
    'The Continental Congress is the room where argument became law. It does not end disagreements — it institutionalizes them, creating a framework that lets competing interests produce a binding outcome without permanent schism.',
    'The historical Continental Congress unified fractious colonial interests through representative debate rather than force. What emerged was not a perfect consensus but a workable structure that could outlast any individual leader.',
    'memory',
    ['science', 'gold', 'culture', 'knowledge', 'ancient'],
    ['loc-about'],
    'image-archive',
    ['science', 'gold', 'culture'],
    'Institutional Design',
    'A congress works because it gives every faction a reason to stay in the room.',
    'Debate as Infrastructure',
    'Its reward fits a civilization that treats governance as a form of technology, continually revised and improved.',
  ),
  legendary(
    'eiffel-tower',
    'Eiffel Tower',
    'Iron made beautiful by ambition.',
    'The Eiffel Tower was denounced as an eyesore by the artists and celebrated as a marvel by the engineers. Both were right. It proved that industrial civilization could produce objects of pure symbolic power — structures that serve no function except to announce that a civilization has arrived.',
    'Designed by Gustave Eiffel for the 1889 World\'s Fair in Paris, the tower used prefabricated iron lattice sections assembled on site. It remained the world\'s tallest structure for 41 years and became the most visited monument on Earth.',
    'ingenuity',
    ['production', 'gold', 'trade', 'industry', 'engineering'],
    ['loc-about'],
    'image-foundry',
    ['production', 'gold', 'trade'],
    'Monument as Statement',
    'A tower that serves no military purpose has a different kind of power: it asserts that beauty itself is a strategic resource.',
    'Industry as Spectacle',
    'Its reward fits a civilization that has learned to turn its industrial capacity outward — not just into goods, but into prestige.',
  ),
  legendary(
    'brooklyn-bridge',
    'Brooklyn Bridge',
    'The span that made a city whole.',
    'The Brooklyn Bridge connected two cities that called themselves rivals and made them one. It did not merely allow people to cross — it changed what it meant to be New York. The bridge is a machine for creating economic mass, pulling trade, labor, and capital across the water it spans.',
    'Completed in 1883, the Brooklyn Bridge was the longest suspension bridge in the world at the time. Its Gothic stone towers and steel cables were an engineering triumph; its social impact was even larger, enabling the growth of New York into a true metropolis.',
    'ingenuity',
    ['production', 'food', 'trade', 'stone', 'water'],
    ['loc-about'],
    'image-foundry',
    ['production', 'food', 'trade'],
    'Infrastructure as Unification',
    'The bridge\'s genius was that it made distance irrelevant for a city that had been limited by its own geography.',
    'Connection as Yield',
    'Its reward fits a civilization that understands that the value of production rises with the scale of the market it can reach.',
  ),
  legendary(
    'trans-siberian-railway',
    'Trans-Siberian Railway',
    'The iron spine of a continent.',
    'The Trans-Siberian Railway did not just cross a landscape — it asserted ownership of it. A civilization that can build a railway across 9,000 kilometers of steppe, taiga, and permafrost does not merely have an empire; it has decided to keep it. The railway converted vast distance from a liability into a resource.',
    'Constructed between 1891 and 1916, the Trans-Siberian Railway is the world\'s longest railway line. It connected Moscow to the Pacific, enabled the rapid transport of troops and settlers, and transformed Siberia from a frozen exile into an economic frontier.',
    'discovery',
    ['production', 'trade', 'military', 'engineering', 'industry'],
    ['loc-about'],
    'image-foundry',
    ['production', 'trade', 'military'],
    'Empire at Scale',
    'The railway proved that the limit of empire is not the distance you can hold, but the speed at which you can respond to its edges.',
    'Production as Reach',
    'Its reward fits a civilization that has outgrown its heartland and needs its whole territory to function as a unit.',
  ),
  legendary(
    'panama-canal',
    'Panama Canal',
    'The shortest path between two oceans.',
    'The Panama Canal did not merely cut through the isthmus — it rewrote the map of global trade. A voyage that once required rounding Cape Horn in weeks could now be accomplished in hours. The canal collapsed distance, and with it, the economic geography of an entire hemisphere.',
    'Completed in 1914 after a decade of American construction on French foundations, the Panama Canal remains one of the greatest engineering achievements of the industrial age. It required defeating yellow fever, moving 200 million cubic yards of earth, and raising and lowering ships 85 feet through a system of locks.',
    'ingenuity',
    ['gold', 'trade', 'engineering', 'water', 'modern'],
    ['loc-about'],
    'image-foundry',
    ['gold', 'trade', 'engineering'],
    'Two Oceans as One',
    'A civilization that commands the bottleneck between hemispheres does not just trade — it taxes the world\'s ambition.',
    'Gold Through the Locks',
    'Its reward fits a civilization whose prosperity depends on the movement of goods across the globe.',
  ),
  legendary(
    'empire-state-building',
    'Empire State Building',
    'A monument to the century of mass ambition.',
    'The Empire State Building was not built to house offices — it was built to prove something. In the middle of the Great Depression, while the world contracted, it pointed upward. Its steel frame said that a civilization which can still build on this scale has not yet decided to stop.',
    'Completed in 1931 in just 410 days, the Empire State Building held the title of world\'s tallest structure for nearly 40 years. It was built during the Great Depression at a cost of $40 million — a defiant investment in vertical ambition when horizontal expansion had stalled.',
    'prosperity',
    ['production', 'gold', 'trade', 'industry', 'modern'],
    ['loc-about'],
    'image-foundry',
    ['production', 'gold', 'industry'],
    'Height as Policy',
    'Civilizations that build the tallest things are rarely the ones that have given up.',
    'Production and Prestige',
    'Its reward fits a civilization that has mastered the industrial transition and now scales it vertically.',
  ),
  legendary(
    'hoover-dam',
    'Hoover Dam',
    'The river tamed; the desert made to bloom.',
    'The Hoover Dam did not just hold back water — it made the desert negotiable. The American Southwest, an inhospitable tangle of canyon and heat, became an agricultural breadbasket and a population center because one concrete arch told the Colorado River where to stop. Power followed; cities followed; the 20th century followed.',
    'Completed in 1936, the Hoover Dam is 726 feet tall and was the largest dam in the world at the time of its construction. It created Lake Mead, the largest reservoir in the United States, and provided the electrical infrastructure that powered the growth of Las Vegas, Los Angeles, and Phoenix.',
    'awe',
    ['food', 'production', 'engineering', 'water', 'modern'],
    ['loc-about'],
    'image-foundry',
    ['food', 'production', 'engineering'],
    'The River Answers',
    'A civilization that can redirect a river does not ask nature for permission.',
    'Food and Foundations',
    'Its reward fits a civilization that is transforming wilderness into civilization through scale and will.',
  ),
] satisfies WonderCodexContent[];

function legendary(
  id: string,
  title: string,
  subtitle: string,
  authoredLead: string,
  learningText: string,
  visualTone: WonderCodexContent['visualTone'],
  tags: WonderCodexContent['tags'],
  factSourceIds: string[],
  imageSourceId: string,
  relatedSeedTags: WonderCodexContent['relatedSeedTags'],
  firstHeading: string,
  firstBody: string,
  secondHeading: string,
  secondBody: string,
): WonderCodexContent {
  return {
    id,
    kind: 'legendary',
    title,
    subtitle,
    authoredLead,
    learningText,
    visualTone,
    tags,
    relatedSeedTags,
    factSourceIds,
    imageSourceId,
    statusHooks: ['legendary-status', 'legendary-reward', 'legendary-host-city', 'legendary-progress'],
    sections: [
      { kind: 'ritual', heading: firstHeading, body: firstBody },
      { kind: 'reward', heading: secondHeading, body: secondBody },
    ],
  };
}
