import type { WonderCodexContent } from '@/systems/wonder-codex/types';

export const NATURAL_WONDER_CODEX_CONTENT = [
  natural(
    'great_volcano',
    'Great Volcano',
    'A mountain that makes creation and ruin visible at the same time.',
    'The Great Volcano dominates its horizon with a lesson no settlement can ignore: the earth is still being made. Its slopes promise rich soil and hard stone, but every gift arrives under a plume of risk.',
    'Real volcanoes build new land from molten rock. Their ash can enrich soil, while eruptions can also endanger farms, towns, and roads.',
    'danger',
    ['fire', 'stone', 'production', 'science', 'nature'],
    ['usgs-volcanoes'],
    'image-volcano',
    ['fire', 'stone', 'nature'],
    'Living Stone',
    'Smoke, mineral color, and exposed rock make the tile feel powerful even before its yields matter.',
    'Settling Near Fire',
    'A city near volcanic ground inherits abundance and anxiety in equal measure.',
  ),
  natural(
    'sacred_mountain',
    'Sacred Mountain',
    'A high place where distance, weather, and belief meet.',
    'The Sacred Mountain rises above ordinary travel. People look up to it for direction, for stories, and for the feeling that the world is larger than any one city.',
    'Mountains are formed by huge geologic forces such as uplift, folding, faulting, and volcanism. Their height changes weather, water, and movement around them.',
    'reverence',
    ['mountain', 'stone', 'faith', 'science', 'sky'],
    ['nps-geology-mountains'],
    'image-mountain',
    ['mountain', 'faith', 'sky'],
    'Above the Roads',
    'Its position makes it a landmark for travelers and a symbol for the people below.',
    'Weather Maker',
    'Mountains can shape clouds, snow, rivers, and the routes cities choose.',
  ),
  natural(
    'crystal_caverns',
    'Crystal Caverns',
    'A hidden world where stone grows slowly in the dark.',
    'The Crystal Caverns feel like a treasury made by patience. Light catches on mineral faces, and every chamber suggests that the underground world has its own architecture.',
    'Caves often form when water dissolves rock over long spans of time. Minerals carried by water can later build crystals, columns, and other cave formations.',
    'mystery',
    ['cave', 'stone', 'gold', 'science', 'discovery'],
    ['nps-caves'],
    'image-cave',
    ['cave', 'stone', 'discovery'],
    'Rooms Below',
    'The caverns make exploration feel vertical: there is a map beneath the map.',
    'Mineral Time',
    'Their treasure is not only wealth, but a record of slow geologic change.',
  ),
  natural(
    'ancient_forest',
    'Ancient Forest',
    'A living library of shade, roots, and old paths.',
    'The Ancient Forest does not announce itself with stone walls. Its power is quieter: layers of branches, soil, animals, and memory that make the city slow down and listen.',
    'Forests shelter many kinds of living things. Older forests can store carbon, protect soil, cool nearby places, and preserve habitats that are hard to replace.',
    'reverence',
    ['forest', 'food', 'healing', 'nature', 'culture'],
    ['usda-forests'],
    'image-forest',
    ['forest', 'healing', 'nature'],
    'Canopy Country',
    'The forest creates a sheltered world where movement, sound, and light all change.',
    'Old Roots',
    'A city that respects the forest gains a story of care instead of only timber.',
  ),
  natural(
    'coral_reef',
    'Coral Reef',
    'A bright city of animals beneath shallow water.',
    'The Coral Reef turns the coast into a living mosaic. Fish weave through branching shapes, and the water itself seems crowded with color and motion.',
    'Corals are tiny animals that can build reef structures. Healthy reefs provide habitat for many marine species and help protect coastlines from waves.',
    'awe',
    ['coast', 'sea', 'food', 'gold', 'nature'],
    ['noaa-corals'],
    'image-coral',
    ['sea', 'food', 'nature'],
    'Underwater Streets',
    'The reef is a habitat, a barrier, and a gathering place at the same time.',
    'Fragile Brightness',
    'Its beauty also teaches that living systems can be powerful and delicate.',
  ),
  natural(
    'grand_canyon',
    'Grand Canyon',
    'A vast cut in the earth that turns deep time into a view.',
    'The Grand Canyon is not a wall but a revelation. Layer after layer shows that the land has a memory longer than any kingdom.',
    'The real Grand Canyon exposes rock layers shaped by water, uplift, and erosion. It is one of the best-known places for seeing geologic time in the landscape.',
    'awe',
    ['canyon', 'stone', 'gold', 'science', 'earth'],
    ['nps-grand-canyon'],
    'image-grand-canyon',
    ['canyon', 'stone', 'earth'],
    'Depth as Defense',
    'The canyon changes movement and sightlines, making the land itself feel fortified.',
    'Layered Memory',
    'Its cliffs make history visible without needing a monument built by people.',
  ),
  natural(
    'aurora_fields',
    'Aurora Fields',
    'Cold ground under curtains of moving sky-light.',
    'The Aurora Fields make night feel awake. Green and violet light moves above the ice, turning a harsh region into a place of wonder.',
    'Auroras happen when charged particles from the Sun interact with gases high in Earths atmosphere, producing glowing curtains near polar regions.',
    'discovery',
    ['aurora', 'sky', 'ice', 'science', 'light'],
    ['nasa-aurora'],
    'image-aurora',
    ['aurora', 'sky', 'science'],
    'Sky Weather',
    'The wonder links the land to events far above it.',
    'Cold Brilliance',
    'Its science reward fits a place where beauty asks questions.',
  ),
  natural(
    'frozen_falls',
    'Frozen Falls',
    'A waterfall caught between motion and stillness.',
    'The Frozen Falls hold a moment that should be impossible: rushing water suspended in white blue silence. Scouts climb for the view and return with stories of scale.',
    'Waterfalls form where water drops suddenly over resistant rock or steep terrain. In freezing weather, spray and flow can build dramatic ice formations.',
    'awe',
    ['ice', 'water', 'stone', 'production', 'science'],
    ['nps-waterfalls'],
    'image-waterfall',
    ['ice', 'water', 'stone'],
    'Stopped Motion',
    'The falls look still, but they are made by movement and cold working together.',
    'High Outlook',
    'A commanding view makes this wonder useful as well as beautiful.',
  ),
  natural(
    'dragon_bones',
    'Dragon Bones',
    'A fossil field big enough to become a legend.',
    'The Dragon Bones make science and myth sit beside each other. What one generation calls a monster, another can study as evidence of ancient life.',
    'Fossils are preserved traces or remains of organisms from the past. They help scientists learn about extinct species and ancient environments.',
    'memory',
    ['fossil', 'stone', 'science', 'military', 'ancient'],
    ['smithsonian-fossils'],
    'image-fossil',
    ['fossil', 'science', 'ancient'],
    'Bones in Stone',
    'The remains give the land a sense of age and warning.',
    'Legend Becomes Evidence',
    'The wonder rewards curiosity about what came before the current age.',
  ),
  natural(
    'singing_sands',
    'Singing Sands',
    'Dunes that turn footsteps and wind into music.',
    'The Singing Sands make the desert audible. Travelers may disagree about the tune, but they remember the place long after the dunes shift behind them.',
    'Some sand dunes can make booming or humming sounds when dry grains slide together. The effect depends on grain size, moisture, and movement.',
    'mystery',
    ['desert', 'gold', 'earth', 'travel', 'culture'],
    ['nps-singing-sands'],
    'image-desert',
    ['desert', 'travel', 'culture'],
    'Sounding Dunes',
    'The desert becomes a landmark for the ear, not only the eye.',
    'Moving Roads',
    'Routes across the sands feel temporary, valuable, and dangerous.',
  ),
  natural(
    'sunken_ruins',
    'Sunken Ruins',
    'A drowned memory where stonework waits below the waves.',
    'The Sunken Ruins suggest that no city is guaranteed forever. Beneath the water, broken walls become reefs for fish and questions for explorers.',
    'Maritime heritage includes shipwrecks, ports, and underwater archaeological sites. These places can preserve evidence of travel, trade, and past communities.',
    'memory',
    ['ocean', 'sea', 'ancient', 'science', 'gold'],
    ['noaa-maritime-heritage'],
    'image-ruins',
    ['ocean', 'ancient', 'science'],
    'Below the Harbor',
    'The ruins make the coast feel layered with forgotten routes.',
    'Careful Recovery',
    'Their value lies in study and protection, not only treasure.',
  ),
  natural(
    'floating_islands',
    'Floating Islands',
    'Stone and green suspended like a question in the sky.',
    'The Floating Islands are the kind of sight that makes maps feel uncertain. They turn ordinary hills into a legend of balance, lift, and impossible roots.',
    'Real islands, arches, cliffs, and mesas can be shaped by erosion, weathering, and uplift. The codex treats the floating version as a fantasy echo of those real land-shaping processes.',
    'mystery',
    ['sky', 'stone', 'nature', 'discovery', 'science'],
    ['nps-geology-mountains'],
    'image-mountain',
    ['sky', 'stone', 'discovery'],
    'Impossible Ground',
    'The wonder makes the player feel that the world still has rules they do not fully know.',
    'High Garden',
    'Its mixed yields fit a place that combines cliff, soil, wind, and mystery.',
  ),
  natural(
    'bioluminescent_bay',
    'Bioluminescent Bay',
    'Water that glows because life is making light.',
    'The Bioluminescent Bay turns every oar stroke into a spark. At night, the coast feels less like an edge and more like a lantern.',
    'Bioluminescence is light made by living organisms through chemical reactions. Some marine organisms can make waves, wakes, and shorelines glow.',
    'awe',
    ['coast', 'sea', 'light', 'gold', 'science'],
    ['noaa-bioluminescence'],
    'image-coral',
    ['sea', 'light', 'science'],
    'Living Light',
    'The bay shows that tiny organisms can transform a whole night landscape.',
    'Quiet Spectacle',
    'Its glow makes exploration feel intimate rather than loud.',
  ),
  natural(
    'bottomless_lake',
    'Bottomless Lake',
    'A deep inland mirror with stories below the surface.',
    'The Bottomless Lake gives nearby people a place for cures, rumors, and careful watercraft. Its darkness makes every reflection feel older than the city.',
    'Lakes connect to the water cycle through rain, rivers, groundwater, and evaporation. Deep lakes can preserve clues about climate and local geology.',
    'mystery',
    ['water', 'healing', 'science', 'nature', 'stone'],
    ['usgs-water-science'],
    'image-lake',
    ['water', 'healing', 'science'],
    'Dark Water',
    'The unknown depth makes the lake feel restorative and unsettling at once.',
    'Reservoir of Stories',
    'A city beside it learns to treat water as memory and resource.',
  ),
  natural(
    'eternal_storm',
    'Eternal Storm',
    'A horizon where warning and wonder never stop flashing.',
    'The Eternal Storm keeps the sea awake. Its lightning is dangerous, but for careful observers it becomes a signal tower written across the clouds.',
    'Severe storms form when unstable air, moisture, lift, and wind patterns combine. Understanding storms helps people prepare warnings and reduce danger.',
    'danger',
    ['storm', 'ocean', 'sky', 'science', 'discovery'],
    ['noaa-severe-weather'],
    'image-storm',
    ['storm', 'sky', 'science'],
    'Weather Wall',
    'The storm makes open water feel alive and tactical.',
    'Reading the Sky',
    'Its vision bonus fits a wonder that rewards attention to distant signs.',
  ),
] satisfies WonderCodexContent[];

function natural(
  id: string,
  title: string,
  subtitle: string,
  authoredLead: string,
  learningText: string,
  visualTone: WonderCodexContent['visualTone'],
  tags: WonderCodexContent['tags'],
  factSourceIds: string[],
  imageSourceId: string,
  relatedSeedTags: WonderCodexContent['relatedSeedTags'],
  firstHeading: string,
  firstBody: string,
  secondHeading: string,
  secondBody: string,
): WonderCodexContent {
  return {
    id,
    kind: 'natural',
    title,
    subtitle,
    authoredLead,
    learningText,
    visualTone,
    tags,
    relatedSeedTags,
    factSourceIds,
    imageSourceId,
    statusHooks: ['natural-effect', 'natural-location'],
    sections: [
      { kind: 'landscape', heading: firstHeading, body: firstBody },
      { kind: 'legacy', heading: secondHeading, body: secondBody },
    ],
  };
}
