import type { WonderCodexVideoSource, WonderCodexVideoSurface } from '@/systems/wonder-codex/types';

export const HARD_VIDEO_ASSET_REVIEW_BYTES = 5 * 1024 * 1024;
export const TARGET_VIDEO_ASSET_BYTES = 2 * 1024 * 1024;

export const WONDER_CODEX_VIDEO_SOURCES = [
  {
    id: 'video-great-volcano-tonga-eruption',
    wonderId: 'great_volcano',
    title: 'Tonga volcano eruption satellite sequence',
    surfaces: ['codex', 'natural-reveal'],
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Tonga_Volcano_Eruption_2022-01-15_0320Z_to_0610Z_Himawari-8_visible.webm',
    creator: 'Japan Meteorological Agency / Digital Typhoon',
    license: 'CC BY 4.0 compatible public data terms',
    attribution: 'Japan Meteorological Agency / Digital Typhoon - CC BY 4.0 compatible public data terms',
    localPath: '/videos/wonders/great-volcano-tonga-eruption.mp4',
    fallbackImageSourceId: 'image-volcano',
    durationSeconds: 4,
    sizeBytes: 837274,
    format: 'MP4/H.264 derivative from WebM source using OpenH264',
    mimeType: 'video/mp4',
    loopNote: 'Satellite eruption sequence trimmed to a short loop for spike evaluation.',
    audio: 'silent',
    batchId: 'stage-3-spike',
  },
  {
    id: 'video-starvault-paranal-observatory',
    wonderId: 'starvault-observatory',
    title: 'Morning observations time-lapse at Paranal',
    surfaces: ['codex', 'legendary-completion'],
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Morning_observations_time-lapse_at_Paranal.webm',
    creator: 'ESO/J. Colosimo',
    license: 'CC BY 4.0',
    attribution: 'ESO/J. Colosimo - CC BY 4.0',
    localPath: '/videos/wonders/starvault-paranal-observatory.mp4',
    fallbackImageSourceId: 'image-observatory',
    durationSeconds: 4,
    sizeBytes: 929955,
    format: 'MP4/H.264 derivative from WebM source using OpenH264',
    mimeType: 'video/mp4',
    loopNote: 'Observatory time-lapse trimmed to a short loop for spike evaluation.',
    audio: 'silent',
    batchId: 'stage-3-spike',
  },
  {
    id: 'video-sacred-mountain-everest-flyover',
    wonderId: 'sacred_mountain',
    title: 'Everest flyover',
    surfaces: ['codex', 'natural-reveal'],
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:EVEREST.webm',
    creator: 'Sgascoin',
    license: 'CC BY-SA 4.0',
    attribution: 'Sgascoin - CC BY-SA 4.0',
    localPath: '/videos/wonders/sacred-mountain-everest-flyover.mp4',
    fallbackImageSourceId: 'image-mountain',
    durationSeconds: 4,
    sizeBytes: 988173,
    format: 'MP4/H.264 derivative from WebM source using OpenH264',
    mimeType: 'video/mp4',
    loopNote: 'Everest source trimmed to a short silent mountain flyover loop for Stage 3B.',
    audio: 'silent',
    batchId: 'stage-3b-batch-2',
  },
  {
    id: 'video-coral-reef-art-park',
    wonderId: 'coral_reef',
    title: 'Coral reef art park',
    surfaces: ['codex', 'natural-reveal'],
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Coral_Reef_Art.webm',
    creator: 'VOA Africa',
    license: 'public domain VOA material',
    attribution: 'VOA Africa - public domain VOA material',
    localPath: '/videos/wonders/coral-reef-art-park.mp4',
    fallbackImageSourceId: 'image-coral',
    durationSeconds: 4,
    sizeBytes: 989121,
    format: 'MP4/H.264 derivative from WebM source using OpenH264',
    mimeType: 'video/mp4',
    loopNote: 'Coral conservation footage trimmed to a short silent underwater loop for Stage 3B.',
    audio: 'silent',
    batchId: 'stage-3b-batch-2',
  },
  {
    id: 'video-grand-canyon-cira-night-fires',
    wonderId: 'grand_canyon',
    title: 'Grand Canyon wildfire satellite sequence',
    surfaces: ['codex', 'natural-reveal'],
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Grand_Canyon_Wildfires_at_Night_(CIRA_2025-07-14_-_nolabels).webm',
    creator: 'CSU/CIRA and NOAA/NESDIS',
    license: 'public domain NOAA material',
    attribution: 'CSU/CIRA and NOAA/NESDIS - public domain NOAA material',
    localPath: '/videos/wonders/grand-canyon-cira-night-fires.mp4',
    fallbackImageSourceId: 'image-grand-canyon',
    durationSeconds: 4,
    sizeBytes: 393653,
    format: 'MP4/H.264 derivative from WebM source using OpenH264',
    mimeType: 'video/mp4',
    loopNote: 'Institutional Grand Canyon-region satellite motion trimmed to a short silent loop for Stage 3B.',
    audio: 'silent',
    batchId: 'stage-3b-batch-2',
  },
  {
    id: 'video-oracle-of-delphi-melies',
    wonderId: 'oracle-of-delphi',
    title: "L'Oracle de Delphes temple sequence",
    surfaces: ['codex', 'legendary-completion'],
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:L%27Oracle_de_Delphes_(1903).webm',
    creator: 'Georges Melies',
    license: 'public domain',
    attribution: 'Georges Melies - public domain',
    localPath: '/videos/wonders/oracle-of-delphi-melies.mp4',
    fallbackImageSourceId: 'image-delphi',
    durationSeconds: 4,
    sizeBytes: 999022,
    format: 'MP4/H.264 derivative from WebM source using OpenH264',
    mimeType: 'video/mp4',
    loopNote: 'Public-domain oracle film trimmed to a short silent temple/oracle loop for Stage 3B.',
    audio: 'silent',
    batchId: 'stage-3b-batch-2',
  },
  {
    id: 'video-grand-canal-gongchen-hangzhou',
    wonderId: 'grand-canal',
    title: 'Grand Canal Gongchen Hangzhou',
    surfaces: ['codex', 'legendary-completion'],
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Grand_Canal_Gongchen_Hangzhou.webm',
    creator: 'Charlie fong',
    license: 'CC BY-SA 4.0',
    attribution: 'Charlie fong - CC BY-SA 4.0',
    localPath: '/videos/wonders/grand-canal-gongchen-hangzhou.mp4',
    fallbackImageSourceId: 'image-canal',
    durationSeconds: 4,
    sizeBytes: 968180,
    format: 'MP4/H.264 derivative from WebM source using OpenH264',
    mimeType: 'video/mp4',
    loopNote: 'Grand Canal footage trimmed to a short silent waterway loop for Stage 3B.',
    audio: 'silent',
    batchId: 'stage-3b-batch-2',
  },
  {
    id: 'video-moonwell-gardens-flower-bloom',
    wonderId: 'moonwell-gardens',
    title: 'Flower blooming time-lapse',
    surfaces: ['codex', 'legendary-completion'],
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Time-lapse_of_a_flower_blooming.webm',
    creator: 'Ajith Samuel',
    license: 'CC BY 3.0',
    attribution: 'Ajith Samuel - CC BY 3.0',
    localPath: '/videos/wonders/moonwell-gardens-flower-bloom.mp4',
    fallbackImageSourceId: 'image-garden',
    durationSeconds: 4,
    sizeBytes: 539730,
    format: 'MP4/H.264 derivative from WebM source using OpenH264',
    mimeType: 'video/mp4',
    loopNote: 'Flower time-lapse trimmed to a short silent garden-growth loop for Stage 3B.',
    audio: 'silent',
    batchId: 'stage-3b-batch-2',
  },
] satisfies WonderCodexVideoSource[];

export function getWonderCodexVideoSources(): WonderCodexVideoSource[] {
  return WONDER_CODEX_VIDEO_SOURCES.map(source => ({
    ...source,
    surfaces: [...source.surfaces],
  }));
}

export function getWonderCodexVideoSource(id: string): WonderCodexVideoSource | undefined {
  return WONDER_CODEX_VIDEO_SOURCES.find(source => source.id === id);
}

export function getWonderCodexVideoSourceForWonder(
  wonderId: string,
  surface: WonderCodexVideoSurface,
): WonderCodexVideoSource | undefined {
  return WONDER_CODEX_VIDEO_SOURCES.find(source =>
    source.wonderId === wonderId && (source.surfaces as readonly WonderCodexVideoSurface[]).includes(surface),
  );
}
